package main

import (
	"encoding/json"
	"strings"

	"github.com/oorbea/JojoOnePieceSimulator2/internal/domain/entities/game"
)

const rulesHeader = `// Code generated by cmd/typegen. DO NOT EDIT.
//
// Source of truth: game.BuildManualRules (apps/backend/internal/domain/entities/game/
// manual_rules.go), computed from the same rule tables and effect resolver the
// game runs. The in-game manual renders this file, so it cannot drift from the
// code. Regenerate with ` + "`make types`" + ` from apps/backend (or
// ` + "`make types-docker`" + `). CI fails if this file is stale.
`

// emitRules renders game.ManualRules as one `as const` TypeScript value. The
// JSON encoding is deterministic (struct field order, no maps), so the output
// is byte-stable for the stale-contracts check.
func emitRules(rules game.ManualRules) string {
	body, err := json.MarshalIndent(rules, "", "  ")
	if err != nil {
		panic("typegen: encoding manual rules: " + err.Error())
	}
	var b strings.Builder
	b.WriteString(rulesHeader)
	b.WriteString("\nexport const MANUAL_RULES = ")
	b.Write(body)
	b.WriteString(" as const\n\nexport type ManualRules = typeof MANUAL_RULES\n")
	return b.String()
}
