package main

import (
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/oorbea/JojoOnePieceSimulator2/internal/domain/enums"
	"github.com/oorbea/JojoOnePieceSimulator2/internal/infrastructure/api/apierr"
	"github.com/oorbea/JojoOnePieceSimulator2/internal/infrastructure/api/dto"
)

const header = `// Code generated by cmd/typegen. DO NOT EDIT.
//
// Source of truth: apps/backend/internal/infrastructure/api/dto and
// apps/backend/internal/domain/enums. Regenerate with ` + "`make types`" + ` from
// apps/backend (or ` + "`make types-docker`" + `). CI fails if this file is stale.
`

// enumAliases are the legacy schema/type names the frontend used before
// migrating to generated contracts, for the handful of enums whose Go type
// name doesn't match the name already in wide use (51 importers of the old
// apps/frontend/src/shared/lib/zod.ts). Every other enum's Go name already
// matches (e.g. PictureStatus -> pictureStatusSchema/PictureStatus), so no
// alias is needed there. Delete an entry once its importers migrate to the
// canonical name.
var enumAliases = map[string]string{
	"rarity":   "PowerRarity",
	"role":     "UserRole",
	"gameMode": "GameModeKind",
}

// aliasOrder keeps enumAliases' emission deterministic (Go map iteration
// isn't).
var aliasOrder = []string{"rarity", "role", "gameMode"}

func emitEnums(enumIdx map[string]enumInfo) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("\nimport { z } from 'zod'\n\n")

	for _, e := range enums.WireEnums {
		info := enumIdx[e.Name]
		schemaVar := enumSchemaVar(e.Name)
		fmt.Fprintf(&b, "export const %s = %s\n", schemaVar, zodEnumLiteral(info.values))
		fmt.Fprintf(&b, "export type %s = z.infer<typeof %s>\n\n", e.Name, schemaVar)
	}

	b.WriteString("// Legacy aliases: existing call sites import these names. Generated from\n")
	b.WriteString("// cmd/typegen's enumAliases table - delete an entry once its importers\n")
	b.WriteString("// migrate to the canonical name above.\n")
	for _, alias := range aliasOrder {
		goName := enumAliases[alias]
		fmt.Fprintf(&b, "export const %sSchema = %s\n", alias, enumSchemaVar(goName))
		fmt.Fprintf(&b, "export type %s = %s\n", upperFirst(alias), goName)
	}
	return b.String()
}

func zodEnumLiteral(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = "'" + v + "'"
	}
	if len(values) <= 4 {
		return "z.enum([" + strings.Join(quoted, ", ") + "])"
	}
	var b strings.Builder
	b.WriteString("z.enum([\n")
	for _, q := range quoted {
		fmt.Fprintf(&b, "  %s,\n", q)
	}
	b.WriteString("])")
	return b.String()
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func emitErrors(reg map[string]*structInfo) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("\nimport { z } from 'zod'\n\n")

	codes := append([]string(nil), apierr.Codes...)
	sort.Strings(codes)
	quoted := make([]string, len(codes))
	for i, c := range codes {
		quoted[i] = "'" + c + "'"
	}
	b.WriteString("export const errorCodeSchema = z.enum([\n")
	for _, q := range quoted {
		fmt.Fprintf(&b, "  %s,\n", q)
	}
	b.WriteString("])\n")
	b.WriteString("export type ErrorCode = z.infer<typeof errorCodeSchema>\n\n")

	// ErrorResponse.code stays z.string().optional() deliberately (not
	// errorCodeSchema): its documented purpose is degrading gracefully to
	// the English `error` fallback when the client doesn't recognize a
	// code, and a strict enum would instead REJECT a code from a newer
	// backend - the opposite of the field's job. See
	// ObsidianVault/contratos-tipos-generados.md.
	b.WriteString(emitStructSchema(reg["ErrorResponse"], reg))
	return b.String()
}

// emitStructSchema renders one non-recursive struct's zod schema + inferred
// type. Recursive structs (self-referencing) use emitRecursiveStruct
// instead.
func emitStructSchema(si *structInfo, reg map[string]*structInfo) string {
	var b strings.Builder
	fmt.Fprintf(&b, "export const %s = z.object({\n", schemaVarFor(si.name))
	for _, f := range si.fields {
		fmt.Fprintf(&b, "  %s: %s,\n", f.jsonName, f.zodExpr)
	}
	b.WriteString("})\n")
	fmt.Fprintf(&b, "export type %s = z.infer<typeof %s>\n\n", si.name, schemaVarFor(si.name))
	return b.String()
}

// emitRecursiveStruct renders a self-referencing struct's TS type literal
// first, then a z.ZodType<X>-annotated schema. The explicit annotation is
// what stops z.lazy() from making z.infer collapse the WHOLE object to
// `any` - the most dangerous failure mode in this generator, because tsc
// reports no error when it happens (any is assignable to everything). See
// ObsidianVault/contratos-tipos-generados.md.
func emitRecursiveStruct(si *structInfo, enumIdx map[string]enumInfo, isRegistered func(string) bool) string {
	var b strings.Builder

	fmt.Fprintf(&b, "export type %s = {\n", si.name)
	for i := 0; i < si.t.NumField(); i++ {
		f := si.t.Field(i)
		jsonName, tsType, optional, ok := tsFieldType(f, si.name, enumIdx, isRegistered)
		if !ok {
			continue
		}
		q := ""
		if optional {
			q = "?"
		}
		fmt.Fprintf(&b, "  %s%s: %s\n", jsonName, q, tsType)
	}
	b.WriteString("}\n")

	fmt.Fprintf(&b, "export const %s: z.ZodType<%s> = z.object({\n", schemaVarFor(si.name), si.name)
	for _, f := range si.fields {
		fmt.Fprintf(&b, "  %s: %s,\n", f.jsonName, f.zodExpr)
	}
	b.WriteString("})\n\n")
	return b.String()
}

// tsFieldType is buildZodExpr's TypeScript-literal counterpart, used only
// by emitRecursiveStruct (every non-recursive struct gets its type purely
// via `z.infer`, which needs no separate type-literal logic).
func tsFieldType(f reflect.StructField, selfName string, enumIdx map[string]enumInfo, isRegistered func(string) bool) (jsonName, tsType string, optional bool, ok bool) {
	jsonTag := f.Tag.Get("json")
	name, _, _ := strings.Cut(jsonTag, ",")
	if name == "-" {
		return "", "", false, false
	}
	if name == "" {
		name = f.Name
	}
	omitempty := strings.Contains(jsonTag, ",omitempty")
	tsTag := f.Tag.Get("ts")

	t := f.Type
	isPtr := t.Kind() == reflect.Pointer
	if isPtr {
		t = t.Elem()
	}
	base := tsTypeForType(t, tsTag, selfName, enumIdx, isRegistered, f)

	switch {
	case isPtr && omitempty:
		return name, base, true, true
	case isPtr:
		return name, base + " | null", false, true
	case omitempty:
		return name, base, true, true
	default:
		return name, base, false, true
	}
}

func tsTypeForType(t reflect.Type, tsTag, selfName string, enumIdx map[string]enumInfo, isRegistered func(string) bool, field reflect.StructField) string {
	if t == timeTimeType {
		return "string"
	}
	switch t.Kind() {
	case reflect.String:
		if tsTag == "" || tsTag == "datetime" {
			return "string"
		}
		e, ok := enumIdx[tsTag]
		if !ok {
			panic(fmt.Sprintf("typegen: field %s: ts tag %q is not a registered enum", field.Name, tsTag))
		}
		return e.goName
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return "number"
	case reflect.Slice:
		elem := t.Elem()
		if elem.Kind() == reflect.String {
			if strings.HasPrefix(tsTag, "[]") {
				e, ok := enumIdx[tsTag[2:]]
				if !ok {
					panic(fmt.Sprintf("typegen: field %s: ts tag %q is not a registered enum", field.Name, tsTag))
				}
				return e.goName + "[]"
			}
			return "string[]"
		}
		if elem.Kind() == reflect.Struct {
			return elem.Name() + "[]"
		}
		panic(fmt.Sprintf("typegen: field %s: unsupported slice element kind %s", field.Name, elem.Kind()))
	case reflect.Map:
		valType := tsTypeForType(t.Elem(), "", selfName, enumIdx, isRegistered, field)
		if tsTag == "map[Locale]" {
			return "Partial<Record<Locale, " + valType + ">>"
		}
		return "Record<string, " + valType + ">"
	case reflect.Struct:
		if t.Name() == selfName {
			return selfName
		}
		if !isRegistered(t.Name()) {
			panic(fmt.Sprintf("typegen: field %s: %s is not a registered struct", field.Name, t.Name()))
		}
		return t.Name()
	default:
		panic(fmt.Sprintf("typegen: field %s: unsupported kind %s", field.Name, t.Kind()))
	}
}

// emitDTO renders dto.ts: every registered struct assigned to the "dto"
// file, in the global topological order restricted to that file.
func emitDTO(reg map[string]*structInfo, order []string, enumIdx map[string]enumInfo, isRegistered func(string) bool) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("\nimport { z } from 'zod'\n")
	b.WriteString(enumImportLine(reg, order, "dto"))
	b.WriteString("\n")

	for _, name := range order {
		si := reg[name]
		if si.file != "dto" {
			continue
		}
		if si.recursive {
			b.WriteString(emitRecursiveStruct(si, enumIdx, isRegistered))
		} else {
			b.WriteString(emitStructSchema(si, reg))
		}
	}
	return b.String()
}

// enumImportLine collects every enum referenced by fields in the structs
// assigned to fileName and renders one `import { ... } from './enums'` line
// importing BOTH the schema (runtime value) and the type name for each.
// The type name is only actually used by a recursive struct's hand-built
// type literal (see emitRecursiveStruct) - importing it unconditionally
// for every enum is simpler than tracking which structs are recursive, and
// an unused named type import is not a TS error.
func enumImportLine(reg map[string]*structInfo, order []string, fileName string) string {
	used := map[string]bool{}
	for _, name := range order {
		si := reg[name]
		if si.file != fileName {
			continue
		}
		for _, f := range si.fields {
			for _, e := range enums.WireEnums {
				if strings.Contains(f.zodExpr, enumSchemaVar(e.Name)) {
					used[enumSchemaVar(e.Name)] = true
					used[e.Name] = true
				}
			}
		}
	}
	if len(used) == 0 {
		return ""
	}
	var names []string
	for v := range used {
		names = append(names, v)
	}
	sort.Strings(names)
	return "import { " + strings.Join(names, ", ") + " } from './enums'\n"
}

// emitWS renders ws.ts: the CLIENT_COMMAND/SERVER_FRAME const objects and
// their discriminated unions, built directly from dto.CommandPayloads/
// FramePayloads (see game_ws.go's doc comment on why those tables exist),
// followed by every registered struct assigned to the "ws" file.
func emitWS(reg map[string]*structInfo, order []string, enumIdx map[string]enumInfo, isRegistered func(string) bool) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("\nimport { z } from 'zod'\n")
	b.WriteString(enumImportLine(reg, order, "ws"))
	b.WriteString(dtoImportLine(reg, order))
	b.WriteString("\n")

	for _, name := range order {
		si := reg[name]
		if si.file != "ws" {
			continue
		}
		b.WriteString(emitStructSchema(si, reg))
	}

	b.WriteString(emitCommandUnion(reg))
	b.WriteString(emitFrameUnion(reg))
	return b.String()
}

// dtoImportLine collects the dto.ts/errors.ts struct schemas ws.ts's
// payload structs or the command/frame unions reference (e.g.
// GameFinishedPayload.Result, GameStateResponse for STATE, ErrorResponse
// for ERROR, UpdateConfigPayload for UPDATE_CONFIG) and renders one import
// line per source file - ErrorResponse lives in errors.ts, not dto.ts, so
// these can't be merged into a single import.
func dtoImportLine(reg map[string]*structInfo, order []string) string {
	usedFrom := map[string]map[string]bool{"dto": {}, "errors": {}}
	add := func(name string) {
		si, ok := reg[name]
		if !ok {
			return
		}
		if si.file == "dto" || si.file == "errors" {
			usedFrom[si.file][schemaVarFor(name)] = true
		}
	}

	for _, name := range order {
		si := reg[name]
		if si.file != "ws" {
			continue
		}
		for _, ref := range si.refs {
			add(ref)
		}
	}
	for _, spec := range dto.FramePayloads {
		if spec.Payload != nil {
			add(reflect.TypeOf(spec.Payload).Name())
		}
	}
	for _, spec := range dto.CommandPayloads {
		if spec.Payload != nil {
			add(reflect.TypeOf(spec.Payload).Name())
		}
	}

	var out strings.Builder
	for _, file := range []string{"dto", "errors"} {
		if len(usedFrom[file]) == 0 {
			continue
		}
		var names []string
		for v := range usedFrom[file] {
			names = append(names, v)
		}
		sort.Strings(names)
		fmt.Fprintf(&out, "import { %s } from './%s'\n", strings.Join(names, ", "), file)
	}
	return out.String()
}

func emitCommandUnion(reg map[string]*structInfo) string {
	var b strings.Builder
	b.WriteString("export const CLIENT_COMMAND = {\n")
	for _, spec := range dto.CommandPayloads {
		fmt.Fprintf(&b, "  %s: %s,\n", constKey(spec.Type), quoteJS(spec.Type))
	}
	b.WriteString("} as const\n\n")
	b.WriteString("export type ClientCommandType = (typeof CLIENT_COMMAND)[keyof typeof CLIENT_COMMAND]\n\n")

	b.WriteString("export const clientCommandSchema = z.discriminatedUnion('type', [\n")
	for _, spec := range dto.CommandPayloads {
		b.WriteString("  z.object({\n")
		fmt.Fprintf(&b, "    type: z.literal(CLIENT_COMMAND.%s),\n", constKey(spec.Type))
		b.WriteString("    requestId: z.string().optional(),\n")
		if spec.Payload == nil {
			b.WriteString("    payload: z.object({}).optional(),\n")
		} else {
			name := reflect.TypeOf(spec.Payload).Name()
			fmt.Fprintf(&b, "    payload: %s,\n", schemaVarFor(name))
		}
		b.WriteString("  }),\n")
	}
	b.WriteString("])\n")
	b.WriteString("export type ClientCommand = z.infer<typeof clientCommandSchema>\n\n")
	return b.String()
}

func emitFrameUnion(reg map[string]*structInfo) string {
	var b strings.Builder
	b.WriteString("export const SERVER_FRAME = {\n")
	for _, spec := range dto.FramePayloads {
		fmt.Fprintf(&b, "  %s: %s,\n", constKey(spec.Type), quoteJS(spec.Type))
	}
	b.WriteString("} as const\n\n")
	b.WriteString("export type ServerFrameType = (typeof SERVER_FRAME)[keyof typeof SERVER_FRAME]\n\n")

	// The options array is written out inline (not built via .map over
	// dto.FramePayloads-derived data) so TypeScript can actually narrow
	// serverFrameSchema's result on `.type` - a discriminated union built
	// dynamically loses that narrowing.
	b.WriteString("export const serverFrameSchema = z.discriminatedUnion('type', [\n")
	for _, spec := range dto.FramePayloads {
		b.WriteString("  z.object({\n")
		fmt.Fprintf(&b, "    type: z.literal(SERVER_FRAME.%s),\n", constKey(spec.Type))
		b.WriteString("    requestId: z.string().optional(),\n")
		if spec.Payload == nil {
			b.WriteString("    payload: z.object({}).optional(),\n")
		} else {
			name := reflect.TypeOf(spec.Payload).Name()
			fmt.Fprintf(&b, "    payload: %s,\n", schemaVarFor(name))
		}
		b.WriteString("  }),\n")
	}
	b.WriteString("])\n")
	b.WriteString("export type ServerFrame = z.infer<typeof serverFrameSchema>\n")
	return b.String()
}

// constKey turns a wire value ("PLAYER_JOINED") into itself - it's already
// a valid JS object-key identifier - kept as a named step so the mapping is
// in one place if that ever stops being true.
func constKey(wireValue string) string { return wireValue }

func quoteJS(s string) string { return "'" + s + "'" }

func emitIndex(reg map[string]*structInfo, order []string) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("\n// Type-only barrel: importing schemas (values) through here would pull\n")
	b.WriteString("// every generated schema into any bundle that imports even one type -\n")
	b.WriteString("// import a schema from './enums', './errors', './dto', or './ws' directly.\n\n")

	var enumNames []string
	for _, e := range enums.WireEnums {
		enumNames = append(enumNames, e.Name)
	}
	fmt.Fprintf(&b, "export type {\n  %s,\n} from './enums'\n", strings.Join(enumNames, ",\n  "))
	b.WriteString("export type { ErrorCode, ErrorResponse } from './errors'\n")

	var dtoNames, wsNames []string
	for _, name := range order {
		switch reg[name].file {
		case "dto":
			dtoNames = append(dtoNames, name)
		case "ws":
			wsNames = append(wsNames, name)
		}
	}
	fmt.Fprintf(&b, "export type {\n  %s,\n} from './dto'\n", strings.Join(dtoNames, ",\n  "))
	fmt.Fprintf(&b, "export type {\n  %s,\n  ClientCommandType,\n  ClientCommand,\n  ServerFrameType,\n  ServerFrame,\n} from './ws'\n", strings.Join(wsNames, ",\n  "))
	return b.String()
}
