package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"reflect"
	"strings"
	"testing"
)

// dtoPackageDir locates internal/infrastructure/api/dto relative to this
// package, without hardcoding a machine-specific absolute path.
const dtoPackageDir = "../../internal/infrastructure/api/dto"

// TestRegistry_CoversEveryExportedStruct AST-scans package dto's non-test
// source for every exported `type X struct { ... }` and fails if one is in
// neither restTypes, wsOnlyTypes, nor nonWireTypeNames. This is what makes
// adding a DTO without registering it a test failure instead of a silent
// gap in the generated TypeScript - the same guarantee
// enums.WireEnums'/registry_test.go gives the enum side.
func TestRegistry_CoversEveryExportedStruct(t *testing.T) {
	registered := make(map[string]bool)
	for _, v := range restTypes {
		registered[reflect.TypeOf(v).Name()] = true
	}
	for _, v := range wsOnlyTypes {
		registered[reflect.TypeOf(v).Name()] = true
	}

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dtoPackageDir, func(fi fs.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)
	if err != nil {
		t.Fatalf("parsing %s: %v", dtoPackageDir, err)
	}

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				gen, ok := decl.(*ast.GenDecl)
				if !ok || gen.Tok != token.TYPE {
					continue
				}
				for _, spec := range gen.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok || !ts.Name.IsExported() {
						continue
					}
					if _, isStruct := ts.Type.(*ast.StructType); !isStruct {
						continue // func types (PictureURLResolver, ...) aren't wire shapes
					}
					name := ts.Name.Name
					if !registered[name] && !nonWireTypeNames[name] {
						t.Errorf("dto.%s is an exported struct not registered in restTypes, wsOnlyTypes, or nonWireTypeNames (registry.go)", name)
					}
				}
			}
		}
	}
}

// TestRegistry_NoDuplicatesBetweenRESTAndWSOnly guards the file-assignment
// invariant emit.go relies on: a type in both lists would get assigned
// whichever file's loop registered it first (map insertion order), silently
// dropping it from the other file's import line.
func TestRegistry_NoDuplicatesBetweenRESTAndWSOnly(t *testing.T) {
	rest := make(map[string]bool)
	for _, v := range restTypes {
		rest[reflect.TypeOf(v).Name()] = true
	}
	for _, v := range wsOnlyTypes {
		name := reflect.TypeOf(v).Name()
		if rest[name] {
			t.Errorf("%s is registered in both restTypes and wsOnlyTypes", name)
		}
	}
}

// TestGenerate_IsDeterministic runs the full pipeline twice and asserts
// byte-identical output - what CI's `contracts` job relies on (it runs
// typegen twice specifically to catch a nondeterminism a single run
// wouldn't reveal, e.g. from unordered map iteration).
func TestGenerate_IsDeterministic(t *testing.T) {
	first := generate()
	second := generate()
	if len(first) != len(second) {
		t.Fatalf("file count changed between runs: %d vs %d", len(first), len(second))
	}
	for name, content := range first {
		if second[name] != content {
			t.Errorf("%s differs between two runs of generate() - nondeterministic output", name)
		}
	}
}

// TestGenerate_EveryFileHasHeader is a cheap sanity check that every
// emitted file carries the DO-NOT-EDIT header cmd/typegen's own doc
// comment promises.
func TestGenerate_EveryFileHasHeader(t *testing.T) {
	for name, content := range generate() {
		if !strings.HasPrefix(content, "// Code generated by cmd/typegen. DO NOT EDIT.") {
			t.Errorf("%s does not start with the generated-code header", name)
		}
	}
}
