const expoConfig = require('eslint-config-expo/flat')
const queryPlugin = require('@tanstack/eslint-plugin-query')
const prettierConfig = require('eslint-config-prettier')
const prettierPlugin = require('eslint-plugin-prettier')
const { defineConfig, globalIgnores } = require('eslint/config')

module.exports = defineConfig([
  globalIgnores(['dist/*', '.expo/*', 'node_modules/*', 'tamagui-web.css']),
  ...expoConfig,
  ...queryPlugin.configs['flat/recommended'],
  prettierConfig,
  {
    plugins: { prettier: prettierPlugin },
    rules: {
      'prettier/prettier': 'warn',
    },
  },
  {
    // tamagui-web.css is generated by @tamagui/metro-plugin at build time
    // (see metro.config.js outputCSS) — it won't exist on disk until then,
    // so the import resolver can never see it ahead of a build.
    files: ['app/_layout.tsx'],
    rules: {
      'import/no-unresolved': 'off',
    },
  },
  {
    // '@/providers/toaster-mount' only resolves via the platform-suffixed
    // pair toaster-mount.web.tsx/toaster-mount.native.tsx (same pattern as
    // bubble-field.web/.native) - the import resolver understands that for
    // relative imports but not through the `@/*` alias, so it flags an
    // otherwise-valid import as unresolved.
    files: ['src/providers/app-providers.tsx'],
    rules: {
      'import/no-unresolved': 'off',
    },
  },
])
