package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

const migrationsDir = "db/migrations"

// runGenerate writes a new goose migration from snapshot.json +
// translations.json. It refuses if computePending finds anything still
// missing/placeholder/stale - a migration must write every locale's final
// text, never a partial or stale one.
func runGenerate(args []string) error {
	fs := flag.NewFlagSet("generate", flag.ExitOnError)
	if err := fs.Parse(args); err != nil {
		return err
	}

	snap, err := readSnapshot()
	if err != nil {
		return err
	}
	overlay, err := readOverlay()
	if err != nil {
		return err
	}
	sources, err := readSources()
	if err != nil {
		return err
	}

	pending, _, needsConfirmation := computePending(snap, overlay, sources)
	if needsConfirmation {
		return fmt.Errorf("some character rows have no confirmed source locale - run `plan` first")
	}
	if len(pending) > 0 {
		return fmt.Errorf("%d translations are still pending - run `plan`, translate them into translations.json, then re-run generate", len(pending))
	}

	next, err := nextMigrationNumber()
	if err != nil {
		return err
	}
	name := fmt.Sprintf("%s_seed_catalog_%s.sql", next, time.Now().UTC().Format("20060102"))
	path := filepath.Join(migrationsDir, name)

	sql := renderMigration(snap, overlay)
	if err := os.WriteFile(path, []byte(sql), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	fmt.Printf("generate: wrote %s\n", path)
	return nil
}

var migrationNumberRe = regexp.MustCompile(`^(\d{5})_`)

// nextMigrationNumber returns the next free 5-digit goose sequence number,
// scanning migrationsDir's existing files.
func nextMigrationNumber() (string, error) {
	entries, err := os.ReadDir(migrationsDir)
	if err != nil {
		return "", fmt.Errorf("reading %s: %w", migrationsDir, err)
	}
	highest := 0
	for _, e := range entries {
		m := migrationNumberRe.FindStringSubmatch(e.Name())
		if m == nil {
			continue
		}
		n, err := strconv.Atoi(m[1])
		if err != nil {
			continue
		}
		if n > highest {
			highest = n
		}
	}
	return fmt.Sprintf("%05d", highest+1), nil
}

// resolved is one row's final translation set for every locale: the source
// locale's text as dumped from prod, plus every overlay entry for the same
// row - the exact text the migration writes, regardless of what prod
// currently has for the non-source locales.
type resolved struct {
	name         string
	translations map[string]Translation // locale -> final text
}

func resolveTranslations(kind, name string, snapRow map[string]Translation, overlay Overlay, sources Sources) resolved {
	sourceLocale, _ := sourceLocaleFor(kind, name, sources)
	out := map[string]Translation{sourceLocale: snapRow[sourceLocale]}
	for _, target := range locales {
		if target == sourceLocale {
			continue
		}
		if entry, ok := overlayFor(&overlay, kind)[name][target]; ok {
			out[target] = Translation{Description: entry.Description, Skills: entry.Skills}
		}
	}
	return resolved{name: name, translations: out}
}

// renderMigration builds the goose SQL migration body. See
// db/migrations/00017_seed_catalog_*.sql itself (once generated) and
// ObsidianVault/catalog-seed-from-prod.md for the full shape this produces:
//   - a full-catalogue block (rows, stats, image keys - never image bytes),
//     gated on SEED_CATALOG_FULL so it only ever runs in local dev/test,
//   - a translations-only block that runs everywhere, upserting only rows
//     whose parent still exists and hasn't been edited since this dump.
func renderMigration(snap Snapshot, overlay Overlay) string {
	var b strings.Builder
	b.WriteString("-- +goose Up\n")
	b.WriteString("-- +goose ENVSUB ON\n")
	b.WriteString("-- Generated by apps/backend/cmd/catalogsync from a prod snapshot taken at ")
	b.WriteString(snap.DumpedAt.Format(time.RFC3339))
	b.WriteString(".\n-- See ObsidianVault/catalog-seed-from-prod.md before hand-editing this file -\n")
	b.WriteString("-- re-run `catalogsync generate` instead so it stays reproducible.\n\n")

	// No PL/pgSQL DO block here on purpose: goose's ENVSUB pass (mfridman/
	// interpolate) only understands ${VAR}/$VAR references, not Postgres's
	// $tag$ dollar-quoting - it happily parses into a dollar-quoted body
	// looking for variable references and corrupts it. Every full-catalogue
	// statement below is instead a plain `INSERT ... SELECT ... WHERE
	// '${SEED_CATALOG_FULL:-false}' = 'true'` (or an UPDATE with the same
	// WHERE guard) - ordinary SQL, no quoting trick needed.
	writeFullCatalogue(&b, snap)
	b.WriteString("\n")
	writeTranslations(&b, snap, overlay)
	b.WriteString("\n-- +goose Down\n")
	b.WriteString("-- Deliberately a no-op: this migration only ever fills in missing/stale\n")
	b.WriteString("-- translations and (local-only) seeds a read-only copy of prod's catalogue.\n")
	b.WriteString("-- Rolling it back would either delete an admin's real prod content or\n")
	b.WriteString("-- silently blank out translations a later run already fixed - see\n")
	b.WriteString("-- 00012_rarity_mythical.sql for the same reasoning.\n")
	b.WriteString("SELECT 1;\n")

	return b.String()
}

// seedGuard is the WHERE-clause fragment every full-catalogue statement
// carries, so it only ever runs where SEED_CATALOG_FULL=true (local dev/
// test) - see docker-compose.dev.yml/.test.yml. Never true in prod.
const seedGuard = "'${SEED_CATALOG_FULL:-false}' = 'true'"

func writeFullCatalogue(b *strings.Builder, snap Snapshot) {
	for _, s := range snap.Stands {
		fmt.Fprintf(b, "INSERT INTO powers (id, kind, name, rarity, picture, picture_thumb, picture_card, picture_lqip, picture_media_id, picture_status, focal_x, focal_y, created_at, updated_at)\n")
		fmt.Fprintf(b, "  SELECT %s, 'STAND', %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s WHERE %s\n  ON CONFLICT (id) DO NOTHING;\n",
			sqlLit(s.ID), sqlLit(s.Name), sqlLit(s.Rarity), sqlLit(s.Picture), sqlLit(s.PictureThumb), sqlLit(s.PictureCard),
			sqlLit(s.PictureLQIP), sqlLit(s.PictureMediaID), sqlLit(s.PictureStatus), sqlFloat(s.FocalX), sqlFloat(s.FocalY),
			sqlTime(s.CreatedAt), sqlTime(s.UpdatedAt), seedGuard)
		fmt.Fprintf(b, "INSERT INTO stands (id, attack_power, speed, attack_range, endurance, \"precision\", potential)\n")
		fmt.Fprintf(b, "  SELECT %s, %s, %s, %s, %s, %s, %s WHERE %s\n  ON CONFLICT (id) DO NOTHING;\n",
			sqlLit(s.ID), sqlLit(s.AttackPower), sqlLit(s.Speed), sqlLit(s.AttackRange), sqlLit(s.Endurance), sqlLit(s.Precision), sqlLit(s.Potential), seedGuard)
	}
	// evolves_from_id is set in a second pass, once every stand row exists -
	// two stands seeded in the same migration may reference each other.
	for _, s := range snap.Stands {
		if s.EvolvesFromID == nil {
			continue
		}
		fmt.Fprintf(b, "UPDATE stands SET evolves_from_id = %s WHERE id = %s AND evolves_from_id IS NULL AND %s;\n", sqlLit(*s.EvolvesFromID), sqlLit(s.ID), seedGuard)
	}

	for _, d := range snap.DevilFruits {
		fmt.Fprintf(b, "INSERT INTO powers (id, kind, name, rarity, picture, picture_thumb, picture_card, picture_lqip, picture_media_id, picture_status, focal_x, focal_y, created_at, updated_at)\n")
		fmt.Fprintf(b, "  SELECT %s, 'DEVIL_FRUIT', %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s WHERE %s\n  ON CONFLICT (id) DO NOTHING;\n",
			sqlLit(d.ID), sqlLit(d.Name), sqlLit(d.Rarity), sqlLit(d.Picture), sqlLit(d.PictureThumb), sqlLit(d.PictureCard),
			sqlLit(d.PictureLQIP), sqlLit(d.PictureMediaID), sqlLit(d.PictureStatus), sqlFloat(d.FocalX), sqlFloat(d.FocalY),
			sqlTime(d.CreatedAt), sqlTime(d.UpdatedAt), seedGuard)
		fmt.Fprintf(b, "INSERT INTO devil_fruits (id, fruit_type) SELECT %s, %s WHERE %s ON CONFLICT (id) DO NOTHING;\n", sqlLit(d.ID), sqlLit(d.FruitType), seedGuard)
	}

	for _, c := range snap.JojoCharacters {
		fmt.Fprintf(b, "INSERT INTO characters (id, manga, name, rarity, picture, picture_thumb, picture_card, picture_lqip, picture_media_id, picture_status, focal_x, focal_y, created_at, updated_at)\n")
		fmt.Fprintf(b, "  SELECT %s, 'JOJO', %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s WHERE %s\n  ON CONFLICT (id) DO NOTHING;\n",
			sqlLit(c.ID), sqlLit(c.Name), sqlLit(c.Rarity), sqlLit(c.Picture), sqlLit(c.PictureThumb), sqlLit(c.PictureCard),
			sqlLit(c.PictureLQIP), sqlLit(c.PictureMediaID), sqlLit(c.PictureStatus), sqlFloat(c.FocalX), sqlFloat(c.FocalY),
			sqlTime(c.CreatedAt), sqlTime(c.UpdatedAt), seedGuard)
		fmt.Fprintf(b, "INSERT INTO jojo_characters (id, hamon, spin, battle_iq) SELECT %s, %s, %s, %d WHERE %s ON CONFLICT (id) DO NOTHING;\n",
			sqlLit(c.ID), sqlLit(c.Hamon), sqlLit(c.Spin), c.BattleIQ, seedGuard)
	}

	for _, c := range snap.OnePieceCharacters {
		fmt.Fprintf(b, "INSERT INTO characters (id, manga, name, rarity, picture, picture_thumb, picture_card, picture_lqip, picture_media_id, picture_status, focal_x, focal_y, created_at, updated_at)\n")
		fmt.Fprintf(b, "  SELECT %s, 'ONE_PIECE', %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s WHERE %s\n  ON CONFLICT (id) DO NOTHING;\n",
			sqlLit(c.ID), sqlLit(c.Name), sqlLit(c.Rarity), sqlLit(c.Picture), sqlLit(c.PictureThumb), sqlLit(c.PictureCard),
			sqlLit(c.PictureLQIP), sqlLit(c.PictureMediaID), sqlLit(c.PictureStatus), sqlFloat(c.FocalX), sqlFloat(c.FocalY),
			sqlTime(c.CreatedAt), sqlTime(c.UpdatedAt), seedGuard)
		fmt.Fprintf(b, "INSERT INTO one_piece_characters (id, physical_form, armament_haki, observation_haki, conqueror_haki, fruit_mastery)\n")
		fmt.Fprintf(b, "  SELECT %s, %s, %s, %s, %s, %s WHERE %s\n  ON CONFLICT (id) DO NOTHING;\n",
			sqlLit(c.ID), sqlLit(c.PhysicalForm), sqlLit(c.ArmamentHaki), sqlLit(c.ObservationHaki), sqlLit(c.ConquerorHaki), sqlLit(c.FruitMastery), seedGuard)
	}

	for _, o := range snap.StorageObjects {
		fmt.Fprintf(b, "INSERT INTO storage_objects (key, provider, bytes) SELECT %s, %s, %d WHERE %s ON CONFLICT (key) DO NOTHING;\n", sqlLit(o.Key), sqlLit(o.Provider), o.Bytes, seedGuard)
	}
	for _, m := range snap.MediaObjects {
		fmt.Fprintf(b, "INSERT INTO media_objects (group_id, variant, storage_key, content_type, bytes, scope) SELECT %s, %s, %s, %s, %d, %s WHERE %s ON CONFLICT (group_id, variant) DO NOTHING;\n",
			sqlLit(m.GroupID), sqlLit(m.Variant), sqlLit(m.StorageKey), sqlLit(m.ContentType), m.Bytes, sqlLit(m.Scope), seedGuard)
	}
}

// writeTranslations upserts power_translations/character_translations for
// every row + locale this migration resolves to, in every environment -
// guarded so it only ever touches a row that (a) still exists and (b)
// hasn't been edited since the source snapshot was taken, so a prod admin
// edit made after the dump always wins over this migration.
func writeTranslations(b *strings.Builder, snap Snapshot, overlay Overlay) {
	type powerRow struct {
		id, kind, name string
		updatedAt      time.Time
	}
	var powers []powerRow
	for _, s := range snap.Stands {
		powers = append(powers, powerRow{s.ID, "stand", s.Name, s.UpdatedAt})
	}
	for _, d := range snap.DevilFruits {
		powers = append(powers, powerRow{d.ID, "devil_fruit", d.Name, d.UpdatedAt})
	}
	sort.Slice(powers, func(i, j int) bool { return powers[i].name < powers[j].name })

	for _, p := range powers {
		snapRow := snapshotTranslations(snap, p.kind, p.id)
		res := resolveWithSourceHint(p.kind, p.name, snapRow, overlay)
		for locale, tr := range res {
			fmt.Fprintf(b, `INSERT INTO power_translations (power_id, locale, description, skills)
SELECT %s, %s, %s, %s
WHERE EXISTS (SELECT 1 FROM powers WHERE id = %s AND updated_at <= %s)
ON CONFLICT (power_id, locale) DO UPDATE
  SET description = EXCLUDED.description, skills = EXCLUDED.skills
  WHERE power_translations.power_id IN (SELECT id FROM powers WHERE id = %s AND updated_at <= %s);
`,
				sqlLit(p.id), sqlLit(locale), sqlLit(tr.Description), sqlTextArray(tr.Skills),
				sqlLit(p.id), sqlTime(p.updatedAt), sqlLit(p.id), sqlTime(p.updatedAt))
		}
	}

	type characterRow struct {
		id, kind, name string
		updatedAt      time.Time
	}
	var characters []characterRow
	for _, c := range snap.JojoCharacters {
		characters = append(characters, characterRow{c.ID, "jojo_character", c.Name, c.UpdatedAt})
	}
	for _, c := range snap.OnePieceCharacters {
		characters = append(characters, characterRow{c.ID, "one_piece_character", c.Name, c.UpdatedAt})
	}
	sort.Slice(characters, func(i, j int) bool { return characters[i].name < characters[j].name })

	for _, c := range characters {
		snapRow := snapshotTranslations(snap, c.kind, c.id)
		res := resolveWithSourceHint(c.kind, c.name, snapRow, overlay)
		for locale, tr := range res {
			fmt.Fprintf(b, `INSERT INTO character_translations (character_id, locale, description)
SELECT %s, %s, %s
WHERE EXISTS (SELECT 1 FROM characters WHERE id = %s AND updated_at <= %s)
ON CONFLICT (character_id, locale) DO UPDATE
  SET description = EXCLUDED.description
  WHERE character_translations.character_id IN (SELECT id FROM characters WHERE id = %s AND updated_at <= %s);
`,
				sqlLit(c.id), sqlLit(locale), sqlLit(tr.Description),
				sqlLit(c.id), sqlTime(c.updatedAt), sqlLit(c.id), sqlTime(c.updatedAt))
		}
	}
}

func snapshotTranslations(snap Snapshot, kind, id string) map[string]Translation {
	for _, s := range snap.Stands {
		if kind == "stand" && s.ID == id {
			return s.Translations
		}
	}
	for _, d := range snap.DevilFruits {
		if kind == "devil_fruit" && d.ID == id {
			return d.Translations
		}
	}
	for _, c := range snap.JojoCharacters {
		if kind == "jojo_character" && c.ID == id {
			return c.Translations
		}
	}
	for _, c := range snap.OnePieceCharacters {
		if kind == "one_piece_character" && c.ID == id {
			return c.Translations
		}
	}
	return nil
}

// resolveWithSourceHint resolves every locale's final text for one row:
// its source locale's text as dumped, plus every overlay translation
// recorded for it. sourceLocaleFor needs `sources`, but by the time
// generate runs every source is already confirmed (computePending would
// have refused otherwise) - callers pass an empty Sources{} since this
// function only reads it for characters, and a missing entry there simply
// means "trust the overlay for every non-empty locale instead".
func resolveWithSourceHint(kind, name string, snapRow map[string]Translation, overlay Overlay) map[string]Translation {
	out := map[string]Translation{}
	for locale, tr := range snapRow {
		out[locale] = tr
	}
	for locale, entry := range overlayFor(&overlay, kind)[name] {
		out[locale] = Translation{Description: entry.Description, Skills: entry.Skills}
	}
	return out
}

func sqlLit(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func sqlFloat(f float64) string {
	return strconv.FormatFloat(f, 'f', -1, 64)
}

func sqlTime(t time.Time) string {
	return "'" + t.UTC().Format(time.RFC3339Nano) + "'::timestamptz"
}

func sqlTextArray(items []string) string {
	if len(items) == 0 {
		return "'{}'::text[]"
	}
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = sqlLit(s)
	}
	return "ARRAY[" + strings.Join(quoted, ",") + "]::text[]"
}
