// Centralizes static asset requires so feature screens don't need brittle
// multi-level relative paths (the old login-screen.tsx reached up 5
// directories to get here).
export const logoAsset = require('../../assets/images/logo.png')

// Victory/defeat cinematic audio (outcome-cinematic.tsx, round-flash.tsx).
// Currently SILENT PLACEHOLDERS generated by
// scripts/generate-silent-placeholder-audio.py, at the exact duration each
// cinematic beat expects - swap the files in assets/audio/ for the owner-
// supplied sound design and this module needs no change. See
// ObsidianVault/game-victory-defeat-cinematic-2026-09-14.md.
export const defeatCinematicSound = require('../../assets/audio/defeat-full.wav')
export const victoryCinematicSound = require('../../assets/audio/victory-full.wav')
export const roundWinSound = require('../../assets/audio/round-win.wav')
export const roundLoseSound = require('../../assets/audio/round-lose.wav')
export const nameTickSound = require('../../assets/audio/name-tick.wav')
