// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: characters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJojoCharacterRows = `-- name: CountJojoCharacterRows :one
SELECT count(*)
FROM jojo_characters j
         JOIN characters c ON c.id = j.id
         LEFT JOIN LATERAL (
    SELECT ct.description
    FROM character_translations ct
    WHERE ct.character_id = c.id AND ct.locale::text = ANY ($1::text[])
    ORDER BY array_position($1::text[], ct.locale::text)
    LIMIT 1
    ) tr ON true
WHERE ($2::power_rarity IS NULL OR c.rarity = $2::power_rarity)
  AND ($3::hamon_level IS NULL OR j.hamon = $3::hamon_level)
  AND ($4::spin_level IS NULL OR j.spin = $4::spin_level)
  AND ($5::smallint IS NULL OR j.battle_iq = $5::smallint)
  AND ($6::text IS NULL
       OR c.name ILIKE '%' || $6::text || '%' ESCAPE '\'
       OR tr.description ILIKE '%' || $6::text || '%' ESCAPE '\')
`

type CountJojoCharacterRowsParams struct {
	Locales  []string
	Rarity   *PowerRarity
	Hamon    *HamonLevel
	Spin     *SpinLevel
	BattleIq *int16
	Search   *string
}

func (q *Queries) CountJojoCharacterRows(ctx context.Context, arg CountJojoCharacterRowsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJojoCharacterRows,
		arg.Locales,
		arg.Rarity,
		arg.Hamon,
		arg.Spin,
		arg.BattleIq,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOnePieceCharacterRows = `-- name: CountOnePieceCharacterRows :one
SELECT count(*)
FROM one_piece_characters o
         JOIN characters c ON c.id = o.id
         LEFT JOIN LATERAL (
    SELECT ct.description
    FROM character_translations ct
    WHERE ct.character_id = c.id AND ct.locale::text = ANY ($1::text[])
    ORDER BY array_position($1::text[], ct.locale::text)
    LIMIT 1
    ) tr ON true
WHERE ($2::power_rarity IS NULL OR c.rarity = $2::power_rarity)
  AND ($3::physical_form IS NULL OR o.physical_form = $3::physical_form)
  AND ($4::haki_level IS NULL OR o.armament_haki = $4::haki_level)
  AND ($5::haki_level IS NULL OR o.observation_haki = $5::haki_level)
  AND ($6::haki_level IS NULL OR o.conqueror_haki = $6::haki_level)
  AND ($7::fruit_mastery IS NULL OR o.fruit_mastery = $7::fruit_mastery)
  AND ($8::text IS NULL
       OR c.name ILIKE '%' || $8::text || '%' ESCAPE '\'
       OR tr.description ILIKE '%' || $8::text || '%' ESCAPE '\')
`

type CountOnePieceCharacterRowsParams struct {
	Locales         []string
	Rarity          *PowerRarity
	PhysicalForm    *PhysicalForm
	ArmamentHaki    *HakiLevel
	ObservationHaki *HakiLevel
	ConquerorHaki   *HakiLevel
	FruitMastery    *FruitMastery
	Search          *string
}

func (q *Queries) CountOnePieceCharacterRows(ctx context.Context, arg CountOnePieceCharacterRowsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOnePieceCharacterRows,
		arg.Locales,
		arg.Rarity,
		arg.PhysicalForm,
		arg.ArmamentHaki,
		arg.ObservationHaki,
		arg.ConquerorHaki,
		arg.FruitMastery,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCharacterByID = `-- name: DeleteCharacterByID :execrows
DELETE FROM characters WHERE id = $1
`

func (q *Queries) DeleteCharacterByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCharacterByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCharacterTranslations = `-- name: DeleteCharacterTranslations :exec
DELETE FROM character_translations WHERE character_id = $1 AND locale::text = ANY ($2::text[])
`

type DeleteCharacterTranslationsParams struct {
	CharacterID pgtype.UUID
	Locales     []string
}

// Deletes translation rows for locales no longer present in an update
// request (en-GB can never be deleted this way - callers must not pass it).
func (q *Queries) DeleteCharacterTranslations(ctx context.Context, arg DeleteCharacterTranslationsParams) error {
	_, err := q.db.Exec(ctx, deleteCharacterTranslations, arg.CharacterID, arg.Locales)
	return err
}

const filterJojoCharacterRows = `-- name: FilterJojoCharacterRows :many
SELECT c.id, c.name, COALESCE(tr.description, '') AS description, c.rarity,
       c.picture, c.picture_thumb, c.picture_card, c.picture_status, c.picture_lqip, c.picture_media_id,
       j.hamon, j.spin, j.battle_iq
FROM jojo_characters j
         JOIN characters c ON c.id = j.id
         LEFT JOIN LATERAL (
    SELECT ct.description
    FROM character_translations ct
    WHERE ct.character_id = c.id AND ct.locale::text = ANY ($1::text[])
    ORDER BY array_position($1::text[], ct.locale::text)
    LIMIT 1
    ) tr ON true
WHERE ($2::power_rarity IS NULL OR c.rarity = $2::power_rarity)
  AND ($3::hamon_level IS NULL OR j.hamon = $3::hamon_level)
  AND ($4::spin_level IS NULL OR j.spin = $4::spin_level)
  AND ($5::smallint IS NULL OR j.battle_iq = $5::smallint)
  AND ($6::text IS NULL
       OR c.name ILIKE '%' || $6::text || '%' ESCAPE '\'
       OR tr.description ILIKE '%' || $6::text || '%' ESCAPE '\')
ORDER BY c.name
`

type FilterJojoCharacterRowsParams struct {
	Locales  []string
	Rarity   *PowerRarity
	Hamon    *HamonLevel
	Spin     *SpinLevel
	BattleIq *int16
	Search   *string
}

type FilterJojoCharacterRowsRow struct {
	ID             pgtype.UUID
	Name           string
	Description    string
	Rarity         string
	Picture        string
	PictureThumb   string
	PictureCard    string
	PictureStatus  string
	PictureLqip    string
	PictureMediaID string
	Hamon          string
	Spin           string
	BattleIq       int16
}

func (q *Queries) FilterJojoCharacterRows(ctx context.Context, arg FilterJojoCharacterRowsParams) ([]FilterJojoCharacterRowsRow, error) {
	rows, err := q.db.Query(ctx, filterJojoCharacterRows,
		arg.Locales,
		arg.Rarity,
		arg.Hamon,
		arg.Spin,
		arg.BattleIq,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterJojoCharacterRowsRow{}
	for rows.Next() {
		var i FilterJojoCharacterRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Rarity,
			&i.Picture,
			&i.PictureThumb,
			&i.PictureCard,
			&i.PictureStatus,
			&i.PictureLqip,
			&i.PictureMediaID,
			&i.Hamon,
			&i.Spin,
			&i.BattleIq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterOnePieceCharacterRows = `-- name: FilterOnePieceCharacterRows :many
SELECT c.id, c.name, COALESCE(tr.description, '') AS description, c.rarity,
       c.picture, c.picture_thumb, c.picture_card, c.picture_status, c.picture_lqip, c.picture_media_id,
       o.physical_form, o.armament_haki, o.observation_haki, o.conqueror_haki, o.fruit_mastery
FROM one_piece_characters o
         JOIN characters c ON c.id = o.id
         LEFT JOIN LATERAL (
    SELECT ct.description
    FROM character_translations ct
    WHERE ct.character_id = c.id AND ct.locale::text = ANY ($1::text[])
    ORDER BY array_position($1::text[], ct.locale::text)
    LIMIT 1
    ) tr ON true
WHERE ($2::power_rarity IS NULL OR c.rarity = $2::power_rarity)
  AND ($3::physical_form IS NULL OR o.physical_form = $3::physical_form)
  AND ($4::haki_level IS NULL OR o.armament_haki = $4::haki_level)
  AND ($5::haki_level IS NULL OR o.observation_haki = $5::haki_level)
  AND ($6::haki_level IS NULL OR o.conqueror_haki = $6::haki_level)
  AND ($7::fruit_mastery IS NULL OR o.fruit_mastery = $7::fruit_mastery)
  AND ($8::text IS NULL
       OR c.name ILIKE '%' || $8::text || '%' ESCAPE '\'
       OR tr.description ILIKE '%' || $8::text || '%' ESCAPE '\')
ORDER BY c.name
`

type FilterOnePieceCharacterRowsParams struct {
	Locales         []string
	Rarity          *PowerRarity
	PhysicalForm    *PhysicalForm
	ArmamentHaki    *HakiLevel
	ObservationHaki *HakiLevel
	ConquerorHaki   *HakiLevel
	FruitMastery    *FruitMastery
	Search          *string
}

type FilterOnePieceCharacterRowsRow struct {
	ID              pgtype.UUID
	Name            string
	Description     string
	Rarity          string
	Picture         string
	PictureThumb    string
	PictureCard     string
	PictureStatus   string
	PictureLqip     string
	PictureMediaID  string
	PhysicalForm    string
	ArmamentHaki    string
	ObservationHaki string
	ConquerorHaki   string
	FruitMastery    string
}

func (q *Queries) FilterOnePieceCharacterRows(ctx context.Context, arg FilterOnePieceCharacterRowsParams) ([]FilterOnePieceCharacterRowsRow, error) {
	rows, err := q.db.Query(ctx, filterOnePieceCharacterRows,
		arg.Locales,
		arg.Rarity,
		arg.PhysicalForm,
		arg.ArmamentHaki,
		arg.ObservationHaki,
		arg.ConquerorHaki,
		arg.FruitMastery,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterOnePieceCharacterRowsRow{}
	for rows.Next() {
		var i FilterOnePieceCharacterRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Rarity,
			&i.Picture,
			&i.PictureThumb,
			&i.PictureCard,
			&i.PictureStatus,
			&i.PictureLqip,
			&i.PictureMediaID,
			&i.PhysicalForm,
			&i.ArmamentHaki,
			&i.ObservationHaki,
			&i.ConquerorHaki,
			&i.FruitMastery,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterTranslations = `-- name: GetCharacterTranslations :many
SELECT character_id, locale, description
FROM character_translations
WHERE character_id = $1
`

// Every translation row for a character, for admin read/write forms that
// need all locales at once instead of one resolved locale.
func (q *Queries) GetCharacterTranslations(ctx context.Context, characterID pgtype.UUID) ([]CharacterTranslation, error) {
	rows, err := q.db.Query(ctx, getCharacterTranslations, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharacterTranslation{}
	for rows.Next() {
		var i CharacterTranslation
		if err := rows.Scan(&i.CharacterID, &i.Locale, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJojoCharacterRowByID = `-- name: GetJojoCharacterRowByID :one
SELECT c.id, c.name, COALESCE(tr.description, '') AS description, c.rarity,
       c.picture, c.picture_thumb, c.picture_card, c.picture_status, c.picture_lqip, c.picture_media_id,
       j.hamon, j.spin, j.battle_iq
FROM jojo_characters j
         JOIN characters c ON c.id = j.id
         LEFT JOIN LATERAL (
    SELECT ct.description
    FROM character_translations ct
    WHERE ct.character_id = c.id AND ct.locale::text = ANY ($2::text[])
    ORDER BY array_position($2::text[], ct.locale::text)
    LIMIT 1
    ) tr ON true
WHERE c.id = $1
`

type GetJojoCharacterRowByIDParams struct {
	ID      pgtype.UUID
	Locales []string
}

type GetJojoCharacterRowByIDRow struct {
	ID             pgtype.UUID
	Name           string
	Description    string
	Rarity         string
	Picture        string
	PictureThumb   string
	PictureCard    string
	PictureStatus  string
	PictureLqip    string
	PictureMediaID string
	Hamon          string
	Spin           string
	BattleIq       int16
}

func (q *Queries) GetJojoCharacterRowByID(ctx context.Context, arg GetJojoCharacterRowByIDParams) (GetJojoCharacterRowByIDRow, error) {
	row := q.db.QueryRow(ctx, getJojoCharacterRowByID, arg.ID, arg.Locales)
	var i GetJojoCharacterRowByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Rarity,
		&i.Picture,
		&i.PictureThumb,
		&i.PictureCard,
		&i.PictureStatus,
		&i.PictureLqip,
		&i.PictureMediaID,
		&i.Hamon,
		&i.Spin,
		&i.BattleIq,
	)
	return i, err
}

const getJojoCharacterRowByName = `-- name: GetJojoCharacterRowByName :one
SELECT c.id, c.name, COALESCE(tr.description, '') AS description, c.rarity,
       c.picture, c.picture_thumb, c.picture_card, c.picture_status, c.picture_lqip, c.picture_media_id,
       j.hamon, j.spin, j.battle_iq
FROM jojo_characters j
         JOIN characters c ON c.id = j.id
         LEFT JOIN LATERAL (
    SELECT ct.description
    FROM character_translations ct
    WHERE ct.character_id = c.id AND ct.locale::text = ANY ($2::text[])
    ORDER BY array_position($2::text[], ct.locale::text)
    LIMIT 1
    ) tr ON true
WHERE c.name = $1
`

type GetJojoCharacterRowByNameParams struct {
	Name    string
	Locales []string
}

type GetJojoCharacterRowByNameRow struct {
	ID             pgtype.UUID
	Name           string
	Description    string
	Rarity         string
	Picture        string
	PictureThumb   string
	PictureCard    string
	PictureStatus  string
	PictureLqip    string
	PictureMediaID string
	Hamon          string
	Spin           string
	BattleIq       int16
}

func (q *Queries) GetJojoCharacterRowByName(ctx context.Context, arg GetJojoCharacterRowByNameParams) (GetJojoCharacterRowByNameRow, error) {
	row := q.db.QueryRow(ctx, getJojoCharacterRowByName, arg.Name, arg.Locales)
	var i GetJojoCharacterRowByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Rarity,
		&i.Picture,
		&i.PictureThumb,
		&i.PictureCard,
		&i.PictureStatus,
		&i.PictureLqip,
		&i.PictureMediaID,
		&i.Hamon,
		&i.Spin,
		&i.BattleIq,
	)
	return i, err
}

const getOnePieceCharacterRowByID = `-- name: GetOnePieceCharacterRowByID :one
SELECT c.id, c.name, COALESCE(tr.description, '') AS description, c.rarity,
       c.picture, c.picture_thumb, c.picture_card, c.picture_status, c.picture_lqip, c.picture_media_id,
       o.physical_form, o.armament_haki, o.observation_haki, o.conqueror_haki, o.fruit_mastery
FROM one_piece_characters o
         JOIN characters c ON c.id = o.id
         LEFT JOIN LATERAL (
    SELECT ct.description
    FROM character_translations ct
    WHERE ct.character_id = c.id AND ct.locale::text = ANY ($2::text[])
    ORDER BY array_position($2::text[], ct.locale::text)
    LIMIT 1
    ) tr ON true
WHERE c.id = $1
`

type GetOnePieceCharacterRowByIDParams struct {
	ID      pgtype.UUID
	Locales []string
}

type GetOnePieceCharacterRowByIDRow struct {
	ID              pgtype.UUID
	Name            string
	Description     string
	Rarity          string
	Picture         string
	PictureThumb    string
	PictureCard     string
	PictureStatus   string
	PictureLqip     string
	PictureMediaID  string
	PhysicalForm    string
	ArmamentHaki    string
	ObservationHaki string
	ConquerorHaki   string
	FruitMastery    string
}

func (q *Queries) GetOnePieceCharacterRowByID(ctx context.Context, arg GetOnePieceCharacterRowByIDParams) (GetOnePieceCharacterRowByIDRow, error) {
	row := q.db.QueryRow(ctx, getOnePieceCharacterRowByID, arg.ID, arg.Locales)
	var i GetOnePieceCharacterRowByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Rarity,
		&i.Picture,
		&i.PictureThumb,
		&i.PictureCard,
		&i.PictureStatus,
		&i.PictureLqip,
		&i.PictureMediaID,
		&i.PhysicalForm,
		&i.ArmamentHaki,
		&i.ObservationHaki,
		&i.ConquerorHaki,
		&i.FruitMastery,
	)
	return i, err
}

const getOnePieceCharacterRowByName = `-- name: GetOnePieceCharacterRowByName :one
SELECT c.id, c.name, COALESCE(tr.description, '') AS description, c.rarity,
       c.picture, c.picture_thumb, c.picture_card, c.picture_status, c.picture_lqip, c.picture_media_id,
       o.physical_form, o.armament_haki, o.observation_haki, o.conqueror_haki, o.fruit_mastery
FROM one_piece_characters o
         JOIN characters c ON c.id = o.id
         LEFT JOIN LATERAL (
    SELECT ct.description
    FROM character_translations ct
    WHERE ct.character_id = c.id AND ct.locale::text = ANY ($2::text[])
    ORDER BY array_position($2::text[], ct.locale::text)
    LIMIT 1
    ) tr ON true
WHERE c.name = $1
`

type GetOnePieceCharacterRowByNameParams struct {
	Name    string
	Locales []string
}

type GetOnePieceCharacterRowByNameRow struct {
	ID              pgtype.UUID
	Name            string
	Description     string
	Rarity          string
	Picture         string
	PictureThumb    string
	PictureCard     string
	PictureStatus   string
	PictureLqip     string
	PictureMediaID  string
	PhysicalForm    string
	ArmamentHaki    string
	ObservationHaki string
	ConquerorHaki   string
	FruitMastery    string
}

func (q *Queries) GetOnePieceCharacterRowByName(ctx context.Context, arg GetOnePieceCharacterRowByNameParams) (GetOnePieceCharacterRowByNameRow, error) {
	row := q.db.QueryRow(ctx, getOnePieceCharacterRowByName, arg.Name, arg.Locales)
	var i GetOnePieceCharacterRowByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Rarity,
		&i.Picture,
		&i.PictureThumb,
		&i.PictureCard,
		&i.PictureStatus,
		&i.PictureLqip,
		&i.PictureMediaID,
		&i.PhysicalForm,
		&i.ArmamentHaki,
		&i.ObservationHaki,
		&i.ConquerorHaki,
		&i.FruitMastery,
	)
	return i, err
}

const listJojoCharacterRows = `-- name: ListJojoCharacterRows :many
SELECT c.id, c.name, COALESCE(tr.description, '') AS description, c.rarity,
       c.picture, c.picture_thumb, c.picture_card, c.picture_status, c.picture_lqip, c.picture_media_id,
       j.hamon, j.spin, j.battle_iq
FROM jojo_characters j
         JOIN characters c ON c.id = j.id
         LEFT JOIN LATERAL (
    SELECT ct.description
    FROM character_translations ct
    WHERE ct.character_id = c.id AND ct.locale::text = ANY ($1::text[])
    ORDER BY array_position($1::text[], ct.locale::text)
    LIMIT 1
    ) tr ON true
ORDER BY c.name
`

type ListJojoCharacterRowsRow struct {
	ID             pgtype.UUID
	Name           string
	Description    string
	Rarity         string
	Picture        string
	PictureThumb   string
	PictureCard    string
	PictureStatus  string
	PictureLqip    string
	PictureMediaID string
	Hamon          string
	Spin           string
	BattleIq       int16
}

func (q *Queries) ListJojoCharacterRows(ctx context.Context, locales []string) ([]ListJojoCharacterRowsRow, error) {
	rows, err := q.db.Query(ctx, listJojoCharacterRows, locales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJojoCharacterRowsRow{}
	for rows.Next() {
		var i ListJojoCharacterRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Rarity,
			&i.Picture,
			&i.PictureThumb,
			&i.PictureCard,
			&i.PictureStatus,
			&i.PictureLqip,
			&i.PictureMediaID,
			&i.Hamon,
			&i.Spin,
			&i.BattleIq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnePieceCharacterRows = `-- name: ListOnePieceCharacterRows :many
SELECT c.id, c.name, COALESCE(tr.description, '') AS description, c.rarity,
       c.picture, c.picture_thumb, c.picture_card, c.picture_status, c.picture_lqip, c.picture_media_id,
       o.physical_form, o.armament_haki, o.observation_haki, o.conqueror_haki, o.fruit_mastery
FROM one_piece_characters o
         JOIN characters c ON c.id = o.id
         LEFT JOIN LATERAL (
    SELECT ct.description
    FROM character_translations ct
    WHERE ct.character_id = c.id AND ct.locale::text = ANY ($1::text[])
    ORDER BY array_position($1::text[], ct.locale::text)
    LIMIT 1
    ) tr ON true
ORDER BY c.name
`

type ListOnePieceCharacterRowsRow struct {
	ID              pgtype.UUID
	Name            string
	Description     string
	Rarity          string
	Picture         string
	PictureThumb    string
	PictureCard     string
	PictureStatus   string
	PictureLqip     string
	PictureMediaID  string
	PhysicalForm    string
	ArmamentHaki    string
	ObservationHaki string
	ConquerorHaki   string
	FruitMastery    string
}

func (q *Queries) ListOnePieceCharacterRows(ctx context.Context, locales []string) ([]ListOnePieceCharacterRowsRow, error) {
	rows, err := q.db.Query(ctx, listOnePieceCharacterRows, locales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOnePieceCharacterRowsRow{}
	for rows.Next() {
		var i ListOnePieceCharacterRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Rarity,
			&i.Picture,
			&i.PictureThumb,
			&i.PictureCard,
			&i.PictureStatus,
			&i.PictureLqip,
			&i.PictureMediaID,
			&i.PhysicalForm,
			&i.ArmamentHaki,
			&i.ObservationHaki,
			&i.ConquerorHaki,
			&i.FruitMastery,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageJojoCharacterRows = `-- name: PageJojoCharacterRows :many
SELECT c.id, c.name, COALESCE(tr.description, '') AS description, c.rarity,
       c.picture, c.picture_thumb, c.picture_card, c.picture_status, c.picture_lqip, c.picture_media_id,
       j.hamon, j.spin, j.battle_iq
FROM jojo_characters j
         JOIN characters c ON c.id = j.id
         LEFT JOIN LATERAL (
    SELECT ct.description
    FROM character_translations ct
    WHERE ct.character_id = c.id AND ct.locale::text = ANY ($1::text[])
    ORDER BY array_position($1::text[], ct.locale::text)
    LIMIT 1
    ) tr ON true
WHERE ($2::power_rarity IS NULL OR c.rarity = $2::power_rarity)
  AND ($3::hamon_level IS NULL OR j.hamon = $3::hamon_level)
  AND ($4::spin_level IS NULL OR j.spin = $4::spin_level)
  AND ($5::smallint IS NULL OR j.battle_iq = $5::smallint)
  AND ($6::text IS NULL
       OR c.name ILIKE '%' || $6::text || '%' ESCAPE '\'
       OR tr.description ILIKE '%' || $6::text || '%' ESCAPE '\')
  AND ($7::text IS NULL OR c.name > $7::text)
ORDER BY c.name
LIMIT $8::int
`

type PageJojoCharacterRowsParams struct {
	Locales   []string
	Rarity    *PowerRarity
	Hamon     *HamonLevel
	Spin      *SpinLevel
	BattleIq  *int16
	Search    *string
	AfterName *string
	PageLimit int32
}

type PageJojoCharacterRowsRow struct {
	ID             pgtype.UUID
	Name           string
	Description    string
	Rarity         string
	Picture        string
	PictureThumb   string
	PictureCard    string
	PictureStatus  string
	PictureLqip    string
	PictureMediaID string
	Hamon          string
	Spin           string
	BattleIq       int16
}

// Keyset-paginated counterpart of FilterJojoCharacterRows - same contract as
// PageDevilFruitRows (devil_fruits.sql): Go passes page_limit = limit + 1
// and detects HasMore from the extra row.
func (q *Queries) PageJojoCharacterRows(ctx context.Context, arg PageJojoCharacterRowsParams) ([]PageJojoCharacterRowsRow, error) {
	rows, err := q.db.Query(ctx, pageJojoCharacterRows,
		arg.Locales,
		arg.Rarity,
		arg.Hamon,
		arg.Spin,
		arg.BattleIq,
		arg.Search,
		arg.AfterName,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageJojoCharacterRowsRow{}
	for rows.Next() {
		var i PageJojoCharacterRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Rarity,
			&i.Picture,
			&i.PictureThumb,
			&i.PictureCard,
			&i.PictureStatus,
			&i.PictureLqip,
			&i.PictureMediaID,
			&i.Hamon,
			&i.Spin,
			&i.BattleIq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageOnePieceCharacterRows = `-- name: PageOnePieceCharacterRows :many
SELECT c.id, c.name, COALESCE(tr.description, '') AS description, c.rarity,
       c.picture, c.picture_thumb, c.picture_card, c.picture_status, c.picture_lqip, c.picture_media_id,
       o.physical_form, o.armament_haki, o.observation_haki, o.conqueror_haki, o.fruit_mastery
FROM one_piece_characters o
         JOIN characters c ON c.id = o.id
         LEFT JOIN LATERAL (
    SELECT ct.description
    FROM character_translations ct
    WHERE ct.character_id = c.id AND ct.locale::text = ANY ($1::text[])
    ORDER BY array_position($1::text[], ct.locale::text)
    LIMIT 1
    ) tr ON true
WHERE ($2::power_rarity IS NULL OR c.rarity = $2::power_rarity)
  AND ($3::physical_form IS NULL OR o.physical_form = $3::physical_form)
  AND ($4::haki_level IS NULL OR o.armament_haki = $4::haki_level)
  AND ($5::haki_level IS NULL OR o.observation_haki = $5::haki_level)
  AND ($6::haki_level IS NULL OR o.conqueror_haki = $6::haki_level)
  AND ($7::fruit_mastery IS NULL OR o.fruit_mastery = $7::fruit_mastery)
  AND ($8::text IS NULL
       OR c.name ILIKE '%' || $8::text || '%' ESCAPE '\'
       OR tr.description ILIKE '%' || $8::text || '%' ESCAPE '\')
  AND ($9::text IS NULL OR c.name > $9::text)
ORDER BY c.name
LIMIT $10::int
`

type PageOnePieceCharacterRowsParams struct {
	Locales         []string
	Rarity          *PowerRarity
	PhysicalForm    *PhysicalForm
	ArmamentHaki    *HakiLevel
	ObservationHaki *HakiLevel
	ConquerorHaki   *HakiLevel
	FruitMastery    *FruitMastery
	Search          *string
	AfterName       *string
	PageLimit       int32
}

type PageOnePieceCharacterRowsRow struct {
	ID              pgtype.UUID
	Name            string
	Description     string
	Rarity          string
	Picture         string
	PictureThumb    string
	PictureCard     string
	PictureStatus   string
	PictureLqip     string
	PictureMediaID  string
	PhysicalForm    string
	ArmamentHaki    string
	ObservationHaki string
	ConquerorHaki   string
	FruitMastery    string
}

func (q *Queries) PageOnePieceCharacterRows(ctx context.Context, arg PageOnePieceCharacterRowsParams) ([]PageOnePieceCharacterRowsRow, error) {
	rows, err := q.db.Query(ctx, pageOnePieceCharacterRows,
		arg.Locales,
		arg.Rarity,
		arg.PhysicalForm,
		arg.ArmamentHaki,
		arg.ObservationHaki,
		arg.ConquerorHaki,
		arg.FruitMastery,
		arg.Search,
		arg.AfterName,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageOnePieceCharacterRowsRow{}
	for rows.Next() {
		var i PageOnePieceCharacterRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Rarity,
			&i.Picture,
			&i.PictureThumb,
			&i.PictureCard,
			&i.PictureStatus,
			&i.PictureLqip,
			&i.PictureMediaID,
			&i.PhysicalForm,
			&i.ArmamentHaki,
			&i.ObservationHaki,
			&i.ConquerorHaki,
			&i.FruitMastery,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacterMediaID = `-- name: UpdateCharacterMediaID :exec
UPDATE characters SET picture_media_id = $1 WHERE id = $2
`

type UpdateCharacterMediaIDParams struct {
	PictureMediaID string
	ID             pgtype.UUID
}

// Sets only a Character's content-addressed media group id - see
// UpdatePowerMediaID (stands.sql).
func (q *Queries) UpdateCharacterMediaID(ctx context.Context, arg UpdateCharacterMediaIDParams) error {
	_, err := q.db.Exec(ctx, updateCharacterMediaID, arg.PictureMediaID, arg.ID)
	return err
}

const updateCharacterPicture = `-- name: UpdateCharacterPicture :exec
UPDATE characters
SET picture          = COALESCE($1::text, picture),
    picture_thumb    = COALESCE($2::text, picture_thumb),
    picture_card     = COALESCE($3::text, picture_card),
    picture_status   = $4::picture_status,
    picture_lqip     = COALESCE($5::text, picture_lqip),
    picture_media_id = COALESCE($6::text, picture_media_id),
    updated_at       = now()
WHERE id = $7
`

type UpdateCharacterPictureParams struct {
	Picture        *string
	PictureThumb   *string
	PictureCard    *string
	PictureStatus  string
	PictureLqip    *string
	PictureMediaID *string
	ID             pgtype.UUID
}

// Updates only a Character's picture renditions and pipeline status,
// without touching name/rarity/translations/stats - same shape as
// UpdatePowerPicture (stands.sql).
func (q *Queries) UpdateCharacterPicture(ctx context.Context, arg UpdateCharacterPictureParams) error {
	_, err := q.db.Exec(ctx, updateCharacterPicture,
		arg.Picture,
		arg.PictureThumb,
		arg.PictureCard,
		arg.PictureStatus,
		arg.PictureLqip,
		arg.PictureMediaID,
		arg.ID,
	)
	return err
}

const upsertCharacter = `-- name: UpsertCharacter :one
INSERT INTO characters (id, manga, name, rarity, picture, picture_thumb, picture_card, picture_status, picture_lqip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE
    SET name           = EXCLUDED.name,
        rarity         = EXCLUDED.rarity,
        picture        = EXCLUDED.picture,
        picture_thumb  = EXCLUDED.picture_thumb,
        picture_card   = EXCLUDED.picture_card,
        picture_status = EXCLUDED.picture_status,
        picture_lqip   = EXCLUDED.picture_lqip,
        updated_at     = now()
RETURNING id
`

type UpsertCharacterParams struct {
	ID            pgtype.UUID
	Manga         string
	Name          string
	Rarity        string
	Picture       string
	PictureThumb  string
	PictureCard   string
	PictureStatus string
	PictureLqip   string
}

func (q *Queries) UpsertCharacter(ctx context.Context, arg UpsertCharacterParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertCharacter,
		arg.ID,
		arg.Manga,
		arg.Name,
		arg.Rarity,
		arg.Picture,
		arg.PictureThumb,
		arg.PictureCard,
		arg.PictureStatus,
		arg.PictureLqip,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertCharacterTranslation = `-- name: UpsertCharacterTranslation :exec
INSERT INTO character_translations (character_id, locale, description)
VALUES ($1, $2, $3)
ON CONFLICT (character_id, locale) DO UPDATE
    SET description = EXCLUDED.description
`

type UpsertCharacterTranslationParams struct {
	CharacterID pgtype.UUID
	Locale      string
	Description string
}

// Upserts a single locale's description for a character. Only en-GB is
// mandatory (like powers, unlike stages) - enforced by the application
// layer's request validation, not here.
func (q *Queries) UpsertCharacterTranslation(ctx context.Context, arg UpsertCharacterTranslationParams) error {
	_, err := q.db.Exec(ctx, upsertCharacterTranslation, arg.CharacterID, arg.Locale, arg.Description)
	return err
}

const upsertJojoCharacter = `-- name: UpsertJojoCharacter :exec
INSERT INTO jojo_characters (id, hamon, spin, battle_iq)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
    SET hamon     = EXCLUDED.hamon,
        spin      = EXCLUDED.spin,
        battle_iq = EXCLUDED.battle_iq
`

type UpsertJojoCharacterParams struct {
	ID       pgtype.UUID
	Hamon    string
	Spin     string
	BattleIq int16
}

func (q *Queries) UpsertJojoCharacter(ctx context.Context, arg UpsertJojoCharacterParams) error {
	_, err := q.db.Exec(ctx, upsertJojoCharacter,
		arg.ID,
		arg.Hamon,
		arg.Spin,
		arg.BattleIq,
	)
	return err
}

const upsertOnePieceCharacter = `-- name: UpsertOnePieceCharacter :exec
INSERT INTO one_piece_characters (id, physical_form, armament_haki, observation_haki, conqueror_haki, fruit_mastery)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE
    SET physical_form    = EXCLUDED.physical_form,
        armament_haki    = EXCLUDED.armament_haki,
        observation_haki = EXCLUDED.observation_haki,
        conqueror_haki   = EXCLUDED.conqueror_haki,
        fruit_mastery    = EXCLUDED.fruit_mastery
`

type UpsertOnePieceCharacterParams struct {
	ID              pgtype.UUID
	PhysicalForm    string
	ArmamentHaki    string
	ObservationHaki string
	ConquerorHaki   string
	FruitMastery    string
}

func (q *Queries) UpsertOnePieceCharacter(ctx context.Context, arg UpsertOnePieceCharacterParams) error {
	_, err := q.db.Exec(ctx, upsertOnePieceCharacter,
		arg.ID,
		arg.PhysicalForm,
		arg.ArmamentHaki,
		arg.ObservationHaki,
		arg.ConquerorHaki,
		arg.FruitMastery,
	)
	return err
}
