// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devil_fruits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDevilFruitByID = `-- name: DeleteDevilFruitByID :execrows
DELETE FROM powers WHERE id = $1 AND kind = 'DEVIL_FRUIT'
`

func (q *Queries) DeleteDevilFruitByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDevilFruitByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const filterDevilFruitRows = `-- name: FilterDevilFruitRows :many
SELECT p.id,
       p.name,
       COALESCE(tr.description, '') AS description,
       p.rarity,
       p.picture,
       p.picture_thumb,
       p.picture_status,
       d.fruit_type,
       COALESCE(tr.skills, '{}')::text[] AS skills
FROM devil_fruits d
         JOIN powers p ON p.id = d.id
         LEFT JOIN LATERAL (
    SELECT pt.description, pt.skills
    FROM power_translations pt
    WHERE pt.power_id = p.id AND pt.locale::text = ANY ($1::text[])
    ORDER BY array_position($1::text[], pt.locale::text)
    LIMIT 1
    ) tr ON true
WHERE ($2::power_rarity IS NULL OR p.rarity = $2::power_rarity)
  AND ($3::fruit_type IS NULL OR d.fruit_type = $3::fruit_type)
  AND ($4::text IS NULL
       OR p.name ILIKE '%' || $4::text || '%' ESCAPE '\'
       OR tr.description ILIKE '%' || $4::text || '%' ESCAPE '\')
ORDER BY p.name
`

type FilterDevilFruitRowsParams struct {
	Locales   []string
	Rarity    *PowerRarity
	FruitType *FruitType
	Search    *string
}

type FilterDevilFruitRowsRow struct {
	ID            pgtype.UUID
	Name          string
	Description   string
	Rarity        string
	Picture       string
	PictureThumb  string
	PictureStatus string
	FruitType     string
	Skills        []string
}

// Returns every devil fruit matching the (all-optional) filters.
func (q *Queries) FilterDevilFruitRows(ctx context.Context, arg FilterDevilFruitRowsParams) ([]FilterDevilFruitRowsRow, error) {
	rows, err := q.db.Query(ctx, filterDevilFruitRows,
		arg.Locales,
		arg.Rarity,
		arg.FruitType,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterDevilFruitRowsRow{}
	for rows.Next() {
		var i FilterDevilFruitRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Rarity,
			&i.Picture,
			&i.PictureThumb,
			&i.PictureStatus,
			&i.FruitType,
			&i.Skills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDevilFruitRowByID = `-- name: GetDevilFruitRowByID :one
SELECT p.id,
       p.name,
       COALESCE(tr.description, '') AS description,
       p.rarity,
       p.picture,
       p.picture_thumb,
       p.picture_status,
       d.fruit_type,
       COALESCE(tr.skills, '{}')::text[] AS skills
FROM devil_fruits d
         JOIN powers p ON p.id = d.id
         LEFT JOIN LATERAL (
    SELECT pt.description, pt.skills
    FROM power_translations pt
    WHERE pt.power_id = p.id AND pt.locale::text = ANY ($2::text[])
    ORDER BY array_position($2::text[], pt.locale::text)
    LIMIT 1
    ) tr ON true
WHERE p.id = $1
`

type GetDevilFruitRowByIDParams struct {
	ID      pgtype.UUID
	Locales []string
}

type GetDevilFruitRowByIDRow struct {
	ID            pgtype.UUID
	Name          string
	Description   string
	Rarity        string
	Picture       string
	PictureThumb  string
	PictureStatus string
	FruitType     string
	Skills        []string
}

// Returns the devil fruit matching `id`, along with its resolved
// description/skills. `locales` is the requested locale's fallback chain,
// most specific first (e.g. ['ca-ES','es-ES','en-GB']) - see
// GetStandRowsByID in stands.sql for the same LATERAL-join pattern.
func (q *Queries) GetDevilFruitRowByID(ctx context.Context, arg GetDevilFruitRowByIDParams) (GetDevilFruitRowByIDRow, error) {
	row := q.db.QueryRow(ctx, getDevilFruitRowByID, arg.ID, arg.Locales)
	var i GetDevilFruitRowByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Rarity,
		&i.Picture,
		&i.PictureThumb,
		&i.PictureStatus,
		&i.FruitType,
		&i.Skills,
	)
	return i, err
}

const getDevilFruitRowByName = `-- name: GetDevilFruitRowByName :one
SELECT p.id,
       p.name,
       COALESCE(tr.description, '') AS description,
       p.rarity,
       p.picture,
       p.picture_thumb,
       p.picture_status,
       d.fruit_type,
       COALESCE(tr.skills, '{}')::text[] AS skills
FROM devil_fruits d
         JOIN powers p ON p.id = d.id
         LEFT JOIN LATERAL (
    SELECT pt.description, pt.skills
    FROM power_translations pt
    WHERE pt.power_id = p.id AND pt.locale::text = ANY ($2::text[])
    ORDER BY array_position($2::text[], pt.locale::text)
    LIMIT 1
    ) tr ON true
WHERE p.name = $1
`

type GetDevilFruitRowByNameParams struct {
	Name    string
	Locales []string
}

type GetDevilFruitRowByNameRow struct {
	ID            pgtype.UUID
	Name          string
	Description   string
	Rarity        string
	Picture       string
	PictureThumb  string
	PictureStatus string
	FruitType     string
	Skills        []string
}

// Same shape as GetDevilFruitRowByID, keyed by name instead of id.
func (q *Queries) GetDevilFruitRowByName(ctx context.Context, arg GetDevilFruitRowByNameParams) (GetDevilFruitRowByNameRow, error) {
	row := q.db.QueryRow(ctx, getDevilFruitRowByName, arg.Name, arg.Locales)
	var i GetDevilFruitRowByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Rarity,
		&i.Picture,
		&i.PictureThumb,
		&i.PictureStatus,
		&i.FruitType,
		&i.Skills,
	)
	return i, err
}

const listDevilFruitRows = `-- name: ListDevilFruitRows :many
SELECT p.id,
       p.name,
       COALESCE(tr.description, '') AS description,
       p.rarity,
       p.picture,
       p.picture_thumb,
       p.picture_status,
       d.fruit_type,
       COALESCE(tr.skills, '{}')::text[] AS skills
FROM devil_fruits d
         JOIN powers p ON p.id = d.id
         LEFT JOIN LATERAL (
    SELECT pt.description, pt.skills
    FROM power_translations pt
    WHERE pt.power_id = p.id AND pt.locale::text = ANY ($1::text[])
    ORDER BY array_position($1::text[], pt.locale::text)
    LIMIT 1
    ) tr ON true
ORDER BY p.name
`

type ListDevilFruitRowsRow struct {
	ID            pgtype.UUID
	Name          string
	Description   string
	Rarity        string
	Picture       string
	PictureThumb  string
	PictureStatus string
	FruitType     string
	Skills        []string
}

// Returns every devil fruit in the system.
func (q *Queries) ListDevilFruitRows(ctx context.Context, locales []string) ([]ListDevilFruitRowsRow, error) {
	rows, err := q.db.Query(ctx, listDevilFruitRows, locales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevilFruitRowsRow{}
	for rows.Next() {
		var i ListDevilFruitRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Rarity,
			&i.Picture,
			&i.PictureThumb,
			&i.PictureStatus,
			&i.FruitType,
			&i.Skills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevilFruit = `-- name: UpsertDevilFruit :exec
INSERT INTO devil_fruits (id, fruit_type)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
    SET fruit_type = EXCLUDED.fruit_type
`

type UpsertDevilFruitParams struct {
	ID        pgtype.UUID
	FruitType string
}

func (q *Queries) UpsertDevilFruit(ctx context.Context, arg UpsertDevilFruitParams) error {
	_, err := q.db.Exec(ctx, upsertDevilFruit, arg.ID, arg.FruitType)
	return err
}

const upsertDevilFruitPower = `-- name: UpsertDevilFruitPower :one
INSERT INTO powers (id, kind, name, rarity, picture, picture_thumb, picture_status)
VALUES ($1, 'DEVIL_FRUIT', $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE
    SET name           = EXCLUDED.name,
        rarity         = EXCLUDED.rarity,
        picture        = EXCLUDED.picture,
        picture_thumb  = EXCLUDED.picture_thumb,
        picture_status = EXCLUDED.picture_status,
        updated_at     = now()
RETURNING id
`

type UpsertDevilFruitPowerParams struct {
	ID            pgtype.UUID
	Name          string
	Rarity        string
	Picture       string
	PictureThumb  string
	PictureStatus string
}

func (q *Queries) UpsertDevilFruitPower(ctx context.Context, arg UpsertDevilFruitPowerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertDevilFruitPower,
		arg.ID,
		arg.Name,
		arg.Rarity,
		arg.Picture,
		arg.PictureThumb,
		arg.PictureStatus,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
