// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listGameResultsByUser = `-- name: ListGameResultsByUser :many
SELECT gr.game_id, gr.mode, gr.winner, gr.rounds_played, gr.aborted, gr.recorded_at
FROM game_results gr
         JOIN game_result_participants grp ON grp.game_id = gr.game_id
WHERE grp.user_id = $1
ORDER BY gr.recorded_at DESC
`

func (q *Queries) ListGameResultsByUser(ctx context.Context, userID pgtype.UUID) ([]GameResult, error) {
	rows, err := q.db.Query(ctx, listGameResultsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameResult{}
	for rows.Next() {
		var i GameResult
		if err := rows.Scan(
			&i.GameID,
			&i.Mode,
			&i.Winner,
			&i.RoundsPlayed,
			&i.Aborted,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordGameResult = `-- name: RecordGameResult :exec
INSERT INTO game_results (game_id, mode, winner, rounds_played, aborted)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (game_id) DO NOTHING
`

type RecordGameResultParams struct {
	GameID       pgtype.UUID
	Mode         string
	Winner       string
	RoundsPlayed int32
	Aborted      bool
}

func (q *Queries) RecordGameResult(ctx context.Context, arg RecordGameResultParams) error {
	_, err := q.db.Exec(ctx, recordGameResult,
		arg.GameID,
		arg.Mode,
		arg.Winner,
		arg.RoundsPlayed,
		arg.Aborted,
	)
	return err
}

const recordGameResultParticipant = `-- name: RecordGameResultParticipant :exec
INSERT INTO game_result_participants (game_id, participant_id, user_id, display_name, team_id, is_bot)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (game_id, participant_id) DO NOTHING
`

type RecordGameResultParticipantParams struct {
	GameID        pgtype.UUID
	ParticipantID pgtype.UUID
	UserID        pgtype.UUID
	DisplayName   string
	TeamID        pgtype.UUID
	IsBot         bool
}

func (q *Queries) RecordGameResultParticipant(ctx context.Context, arg RecordGameResultParticipantParams) error {
	_, err := q.db.Exec(ctx, recordGameResultParticipant,
		arg.GameID,
		arg.ParticipantID,
		arg.UserID,
		arg.DisplayName,
		arg.TeamID,
		arg.IsBot,
	)
	return err
}
