// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"
)

const getMediaObjectsByGroup = `-- name: GetMediaObjectsByGroup :many
SELECT group_id, variant, storage_key, content_type, bytes, scope
FROM media_objects
WHERE group_id = $1
`

type GetMediaObjectsByGroupRow struct {
	GroupID     string
	Variant     string
	StorageKey  string
	ContentType string
	Bytes       int64
	Scope       string
}

// Every variant row for a group, for the media handler's card->thumb->main
// fallback ladder (a group backfilled or transcoded before "card" existed
// may only have thumb/main).
func (q *Queries) GetMediaObjectsByGroup(ctx context.Context, groupID string) ([]GetMediaObjectsByGroupRow, error) {
	rows, err := q.db.Query(ctx, getMediaObjectsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMediaObjectsByGroupRow{}
	for rows.Next() {
		var i GetMediaObjectsByGroupRow
		if err := rows.Scan(
			&i.GroupID,
			&i.Variant,
			&i.StorageKey,
			&i.ContentType,
			&i.Bytes,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMediaObject = `-- name: UpsertMediaObject :exec
INSERT INTO media_objects (group_id, variant, storage_key, content_type, bytes, scope)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (group_id, variant) DO UPDATE
    SET storage_key  = EXCLUDED.storage_key,
        content_type = EXCLUDED.content_type,
        bytes        = EXCLUDED.bytes,
        scope        = EXCLUDED.scope
`

type UpsertMediaObjectParams struct {
	GroupID     string
	Variant     string
	StorageKey  string
	ContentType string
	Bytes       int64
	Scope       string
}

// Upserts one variant's row for a group - called once per card/thumb/main
// after a successful transcode. ON CONFLICT keeps scope/content_type/bytes
// in sync with whatever the latest write says, though in practice a given
// (group_id, variant) pair is only ever written once: group_id is derived
// from the bytes themselves, so re-uploading identical content always
// produces the same group and the same row.
func (q *Queries) UpsertMediaObject(ctx context.Context, arg UpsertMediaObjectParams) error {
	_, err := q.db.Exec(ctx, upsertMediaObject,
		arg.GroupID,
		arg.Variant,
		arg.StorageKey,
		arg.ContentType,
		arg.Bytes,
		arg.Scope,
	)
	return err
}
