// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PowerKind string

const (
	PowerKindSTAND      PowerKind = "STAND"
	PowerKindDEVILFRUIT PowerKind = "DEVIL_FRUIT"
)

func (e *PowerKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PowerKind(s)
	case string:
		*e = PowerKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PowerKind: %T", src)
	}
	return nil
}

type NullPowerKind struct {
	PowerKind PowerKind
	Valid     bool // Valid is true if PowerKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPowerKind) Scan(value interface{}) error {
	if value == nil {
		ns.PowerKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PowerKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPowerKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PowerKind), nil
}

type PowerRarity string

const (
	PowerRarityCOMMON    PowerRarity = "COMMON"
	PowerRarityRARE      PowerRarity = "RARE"
	PowerRarityEPIC      PowerRarity = "EPIC"
	PowerRarityLEGENDARY PowerRarity = "LEGENDARY"
)

func (e *PowerRarity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PowerRarity(s)
	case string:
		*e = PowerRarity(s)
	default:
		return fmt.Errorf("unsupported scan type for PowerRarity: %T", src)
	}
	return nil
}

type NullPowerRarity struct {
	PowerRarity PowerRarity
	Valid       bool // Valid is true if PowerRarity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPowerRarity) Scan(value interface{}) error {
	if value == nil {
		ns.PowerRarity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PowerRarity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPowerRarity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PowerRarity), nil
}

type StandStat string

const (
	StandStatE        StandStat = "E"
	StandStatD        StandStat = "D"
	StandStatC        StandStat = "C"
	StandStatB        StandStat = "B"
	StandStatA        StandStat = "A"
	StandStatINFINITE StandStat = "INFINITE"
	StandStatNULL     StandStat = "NULL"
)

func (e *StandStat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StandStat(s)
	case string:
		*e = StandStat(s)
	default:
		return fmt.Errorf("unsupported scan type for StandStat: %T", src)
	}
	return nil
}

type NullStandStat struct {
	StandStat StandStat
	Valid     bool // Valid is true if StandStat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStandStat) Scan(value interface{}) error {
	if value == nil {
		ns.StandStat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StandStat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStandStat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StandStat), nil
}

type UserRole string

const (
	UserRoleREGULAR UserRole = "REGULAR"
	UserRoleADMIN   UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Power struct {
	ID          pgtype.UUID
	Kind        string
	Name        string
	Description string
	Rarity      string
	Picture     string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PowerSkill struct {
	PowerID  pgtype.UUID
	Position int32
	Skill    string
}

type Stand struct {
	ID            pgtype.UUID
	Kind          string
	AttackPower   string
	Speed         string
	AttackRange   string
	Endurance     string
	Precision     string
	Potential     string
	EvolvesFromID pgtype.UUID
}

type User struct {
	ID           pgtype.UUID
	GoogleSub    string
	Email        string
	Username     string
	CompleteName string
	Picture      string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
