// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type FruitMastery string

const (
	FruitMasteryNONE     FruitMastery = "NONE"
	FruitMasteryREGULAR  FruitMastery = "REGULAR"
	FruitMasteryADVANCED FruitMastery = "ADVANCED"
	FruitMasteryAWAKENED FruitMastery = "AWAKENED"
)

func (e *FruitMastery) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FruitMastery(s)
	case string:
		*e = FruitMastery(s)
	default:
		return fmt.Errorf("unsupported scan type for FruitMastery: %T", src)
	}
	return nil
}

type NullFruitMastery struct {
	FruitMastery FruitMastery
	Valid        bool // Valid is true if FruitMastery is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFruitMastery) Scan(value interface{}) error {
	if value == nil {
		ns.FruitMastery, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FruitMastery.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFruitMastery) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FruitMastery), nil
}

type FruitType string

const (
	FruitTypePARAMECIA        FruitType = "PARAMECIA"
	FruitTypeZOAN             FruitType = "ZOAN"
	FruitTypeLOGIA            FruitType = "LOGIA"
	FruitTypeSPECIALPARAMECIA FruitType = "SPECIAL_PARAMECIA"
	FruitTypeANCIENTZOAN      FruitType = "ANCIENT_ZOAN"
	FruitTypeMYTHICALZOAN     FruitType = "MYTHICAL_ZOAN"
)

func (e *FruitType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FruitType(s)
	case string:
		*e = FruitType(s)
	default:
		return fmt.Errorf("unsupported scan type for FruitType: %T", src)
	}
	return nil
}

type NullFruitType struct {
	FruitType FruitType
	Valid     bool // Valid is true if FruitType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFruitType) Scan(value interface{}) error {
	if value == nil {
		ns.FruitType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FruitType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFruitType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FruitType), nil
}

type GameMode string

const (
	GameModeGAUNTLET GameMode = "GAUNTLET"
	GameModeVERSUS   GameMode = "VERSUS"
)

func (e *GameMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GameMode(s)
	case string:
		*e = GameMode(s)
	default:
		return fmt.Errorf("unsupported scan type for GameMode: %T", src)
	}
	return nil
}

type NullGameMode struct {
	GameMode GameMode
	Valid    bool // Valid is true if GameMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGameMode) Scan(value interface{}) error {
	if value == nil {
		ns.GameMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GameMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGameMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GameMode), nil
}

type HakiLevel string

const (
	HakiLevelNONE           HakiLevel = "NONE"
	HakiLevelPRIVATE        HakiLevel = "PRIVATE"
	HakiLevelVICEADMIRAL    HakiLevel = "VICE_ADMIRAL"
	HakiLevelYONKOCOMMANDER HakiLevel = "YONKO_COMMANDER"
	HakiLevelYONKOPLUS      HakiLevel = "YONKO_PLUS"
)

func (e *HakiLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HakiLevel(s)
	case string:
		*e = HakiLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for HakiLevel: %T", src)
	}
	return nil
}

type NullHakiLevel struct {
	HakiLevel HakiLevel
	Valid     bool // Valid is true if HakiLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHakiLevel) Scan(value interface{}) error {
	if value == nil {
		ns.HakiLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HakiLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHakiLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HakiLevel), nil
}

type HamonLevel string

const (
	HamonLevelNONE     HamonLevel = "NONE"
	HamonLevelBASIC    HamonLevel = "BASIC"
	HamonLevelADVANCED HamonLevel = "ADVANCED"
	HamonLevelPERFECT  HamonLevel = "PERFECT"
)

func (e *HamonLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HamonLevel(s)
	case string:
		*e = HamonLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for HamonLevel: %T", src)
	}
	return nil
}

type NullHamonLevel struct {
	HamonLevel HamonLevel
	Valid      bool // Valid is true if HamonLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHamonLevel) Scan(value interface{}) error {
	if value == nil {
		ns.HamonLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HamonLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHamonLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HamonLevel), nil
}

type Locale string

const (
	LocaleEnGB Locale = "en-GB"
	LocaleEsES Locale = "es-ES"
	LocaleCaES Locale = "ca-ES"
)

func (e *Locale) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Locale(s)
	case string:
		*e = Locale(s)
	default:
		return fmt.Errorf("unsupported scan type for Locale: %T", src)
	}
	return nil
}

type NullLocale struct {
	Locale Locale
	Valid  bool // Valid is true if Locale is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocale) Scan(value interface{}) error {
	if value == nil {
		ns.Locale, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Locale.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocale) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Locale), nil
}

type Manga string

const (
	MangaJOJO     Manga = "JOJO"
	MangaONEPIECE Manga = "ONE_PIECE"
)

func (e *Manga) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Manga(s)
	case string:
		*e = Manga(s)
	default:
		return fmt.Errorf("unsupported scan type for Manga: %T", src)
	}
	return nil
}

type NullManga struct {
	Manga Manga
	Valid bool // Valid is true if Manga is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullManga) Scan(value interface{}) error {
	if value == nil {
		ns.Manga, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Manga.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullManga) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Manga), nil
}

type PhysicalForm string

const (
	PhysicalFormPRIVATE        PhysicalForm = "PRIVATE"
	PhysicalFormSTRONGFISHMAN  PhysicalForm = "STRONG_FISHMAN"
	PhysicalFormMARINECAPTAIN  PhysicalForm = "MARINE_CAPTAIN"
	PhysicalFormVICEADMIRAL    PhysicalForm = "VICE_ADMIRAL"
	PhysicalFormYONKOCOMMANDER PhysicalForm = "YONKO_COMMANDER"
	PhysicalFormYONKOPLUS      PhysicalForm = "YONKO_PLUS"
)

func (e *PhysicalForm) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PhysicalForm(s)
	case string:
		*e = PhysicalForm(s)
	default:
		return fmt.Errorf("unsupported scan type for PhysicalForm: %T", src)
	}
	return nil
}

type NullPhysicalForm struct {
	PhysicalForm PhysicalForm
	Valid        bool // Valid is true if PhysicalForm is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPhysicalForm) Scan(value interface{}) error {
	if value == nil {
		ns.PhysicalForm, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PhysicalForm.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPhysicalForm) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PhysicalForm), nil
}

type PictureStatus string

const (
	PictureStatusNONE    PictureStatus = "NONE"
	PictureStatusPENDING PictureStatus = "PENDING"
	PictureStatusREADY   PictureStatus = "READY"
	PictureStatusFAILED  PictureStatus = "FAILED"
)

func (e *PictureStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PictureStatus(s)
	case string:
		*e = PictureStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PictureStatus: %T", src)
	}
	return nil
}

type NullPictureStatus struct {
	PictureStatus PictureStatus
	Valid         bool // Valid is true if PictureStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPictureStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PictureStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PictureStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPictureStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PictureStatus), nil
}

type PowerKind string

const (
	PowerKindSTAND      PowerKind = "STAND"
	PowerKindDEVILFRUIT PowerKind = "DEVIL_FRUIT"
)

func (e *PowerKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PowerKind(s)
	case string:
		*e = PowerKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PowerKind: %T", src)
	}
	return nil
}

type NullPowerKind struct {
	PowerKind PowerKind
	Valid     bool // Valid is true if PowerKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPowerKind) Scan(value interface{}) error {
	if value == nil {
		ns.PowerKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PowerKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPowerKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PowerKind), nil
}

type PowerRarity string

const (
	PowerRarityCOMMON    PowerRarity = "COMMON"
	PowerRarityRARE      PowerRarity = "RARE"
	PowerRarityEPIC      PowerRarity = "EPIC"
	PowerRarityLEGENDARY PowerRarity = "LEGENDARY"
	PowerRarityMYTHICAL  PowerRarity = "MYTHICAL"
)

func (e *PowerRarity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PowerRarity(s)
	case string:
		*e = PowerRarity(s)
	default:
		return fmt.Errorf("unsupported scan type for PowerRarity: %T", src)
	}
	return nil
}

type NullPowerRarity struct {
	PowerRarity PowerRarity
	Valid       bool // Valid is true if PowerRarity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPowerRarity) Scan(value interface{}) error {
	if value == nil {
		ns.PowerRarity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PowerRarity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPowerRarity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PowerRarity), nil
}

type SpinLevel string

const (
	SpinLevelNONE     SpinLevel = "NONE"
	SpinLevelBASIC    SpinLevel = "BASIC"
	SpinLevelGOLDEN   SpinLevel = "GOLDEN"
	SpinLevelINFINITE SpinLevel = "INFINITE"
)

func (e *SpinLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SpinLevel(s)
	case string:
		*e = SpinLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for SpinLevel: %T", src)
	}
	return nil
}

type NullSpinLevel struct {
	SpinLevel SpinLevel
	Valid     bool // Valid is true if SpinLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSpinLevel) Scan(value interface{}) error {
	if value == nil {
		ns.SpinLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SpinLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSpinLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SpinLevel), nil
}

type StandStat string

const (
	StandStatE        StandStat = "E"
	StandStatD        StandStat = "D"
	StandStatC        StandStat = "C"
	StandStatB        StandStat = "B"
	StandStatA        StandStat = "A"
	StandStatINFINITE StandStat = "INFINITE"
	StandStatNULL     StandStat = "NULL"
)

func (e *StandStat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StandStat(s)
	case string:
		*e = StandStat(s)
	default:
		return fmt.Errorf("unsupported scan type for StandStat: %T", src)
	}
	return nil
}

type NullStandStat struct {
	StandStat StandStat
	Valid     bool // Valid is true if StandStat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStandStat) Scan(value interface{}) error {
	if value == nil {
		ns.StandStat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StandStat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStandStat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StandStat), nil
}

type UserRole string

const (
	UserRoleREGULAR UserRole = "REGULAR"
	UserRoleADMIN   UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Character struct {
	ID             pgtype.UUID
	Manga          string
	Name           string
	Rarity         string
	Picture        string
	PictureThumb   string
	PictureCard    string
	PictureLqip    string
	PictureStatus  string
	PictureMediaID string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type CharacterTranslation struct {
	CharacterID pgtype.UUID
	Locale      string
	Description string
}

type DevilFruit struct {
	ID        pgtype.UUID
	Kind      string
	FruitType string
}

type GameResult struct {
	GameID       pgtype.UUID
	Mode         string
	Winner       string
	RoundsPlayed int32
	Aborted      bool
	RecordedAt   pgtype.Timestamptz
}

type GameResultParticipant struct {
	GameID        pgtype.UUID
	ParticipantID pgtype.UUID
	UserID        pgtype.UUID
	DisplayName   string
	TeamID        pgtype.UUID
	IsBot         bool
}

type JojoCharacter struct {
	ID       pgtype.UUID
	Manga    string
	Hamon    string
	Spin     string
	BattleIq int16
}

type MediaObject struct {
	GroupID     string
	Variant     string
	StorageKey  string
	ContentType string
	Bytes       int64
	Scope       string
	CreatedAt   pgtype.Timestamptz
}

type OnePieceCharacter struct {
	ID              pgtype.UUID
	Manga           string
	PhysicalForm    string
	ArmamentHaki    string
	ObservationHaki string
	ConquerorHaki   string
	FruitMastery    string
}

type Power struct {
	ID             pgtype.UUID
	Kind           string
	Name           string
	Rarity         string
	Picture        string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	PictureThumb   string
	PictureStatus  string
	PictureCard    string
	PictureLqip    string
	PictureMediaID string
}

type PowerTranslation struct {
	PowerID     pgtype.UUID
	Locale      string
	Description string
	Skills      []string
}

type Stage struct {
	ID             pgtype.UUID
	Manga          string
	Position       int32
	Name           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Picture        string
	PictureThumb   string
	PictureStatus  string
	PictureCard    string
	PictureLqip    string
	PictureMediaID string
}

type StageTranslation struct {
	StageID     pgtype.UUID
	Locale      string
	Description string
}

type Stand struct {
	ID            pgtype.UUID
	Kind          string
	AttackPower   string
	Speed         string
	AttackRange   string
	Endurance     string
	Precision     string
	Potential     string
	EvolvesFromID pgtype.UUID
}

type StorageObject struct {
	Key       string
	Provider  string
	Bytes     int64
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	GoogleSub      string
	Email          string
	Username       string
	CompleteName   string
	GooglePicture  string
	Role           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	AvatarKey      string
	AvatarThumbKey string
	AvatarStatus   string
	Language       string
	AvatarCardKey  string
	AvatarLqip     string
	AvatarMediaID  string
}
