// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :exec
DELETE FROM push_subscriptions
WHERE endpoint = $1
`

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, deletePushSubscriptionByEndpoint, endpoint)
	return err
}

const deletePushSubscriptionForUser = `-- name: DeletePushSubscriptionForUser :exec
DELETE FROM push_subscriptions
WHERE user_id = $1 AND endpoint = $2
`

type DeletePushSubscriptionForUserParams struct {
	UserID   pgtype.UUID
	Endpoint string
}

func (q *Queries) DeletePushSubscriptionForUser(ctx context.Context, arg DeletePushSubscriptionForUserParams) error {
	_, err := q.db.Exec(ctx, deletePushSubscriptionForUser, arg.UserID, arg.Endpoint)
	return err
}

const listPushSubscriptionsByUser = `-- name: ListPushSubscriptionsByUser :many
SELECT id, user_id, endpoint, p256dh, auth, created_at, last_seen_at
FROM push_subscriptions
WHERE user_id = $1
ORDER BY last_seen_at DESC
`

func (q *Queries) ListPushSubscriptionsByUser(ctx context.Context, userID pgtype.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trimPushSubscriptionsForUser = `-- name: TrimPushSubscriptionsForUser :exec
DELETE FROM push_subscriptions AS target
WHERE target.user_id = $1
  AND target.id NOT IN (
      SELECT keep.id
      FROM push_subscriptions AS keep
      WHERE keep.user_id = $1
      ORDER BY keep.last_seen_at DESC
      LIMIT $2
  )
`

type TrimPushSubscriptionsForUserParams struct {
	UserID pgtype.UUID
	Limit  int32
}

// Keeps only the $2 most recently seen subscriptions of a user, so a user
// cannot accumulate unbounded endpoints (each one costs a delivery attempt
// per notification).
func (q *Queries) TrimPushSubscriptionsForUser(ctx context.Context, arg TrimPushSubscriptionsForUserParams) error {
	_, err := q.db.Exec(ctx, trimPushSubscriptionsForUser, arg.UserID, arg.Limit)
	return err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :exec
INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4)
ON CONFLICT (endpoint) DO UPDATE
SET user_id      = EXCLUDED.user_id,
    p256dh       = EXCLUDED.p256dh,
    auth         = EXCLUDED.auth,
    last_seen_at = now()
`

type UpsertPushSubscriptionParams struct {
	UserID   pgtype.UUID
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	return err
}
