// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStageByID = `-- name: DeleteStageByID :execrows
DELETE FROM stages WHERE id = $1
`

func (q *Queries) DeleteStageByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStageByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStageByID = `-- name: GetStageByID :one
SELECT id, manga, position, name FROM stages WHERE id = $1
`

type GetStageByIDRow struct {
	ID       pgtype.UUID
	Manga    string
	Position int32
	Name     string
}

func (q *Queries) GetStageByID(ctx context.Context, id pgtype.UUID) (GetStageByIDRow, error) {
	row := q.db.QueryRow(ctx, getStageByID, id)
	var i GetStageByIDRow
	err := row.Scan(
		&i.ID,
		&i.Manga,
		&i.Position,
		&i.Name,
	)
	return i, err
}

const listStages = `-- name: ListStages :many
SELECT id, manga, position, name FROM stages ORDER BY manga, position, name
`

type ListStagesRow struct {
	ID       pgtype.UUID
	Manga    string
	Position int32
	Name     string
}

func (q *Queries) ListStages(ctx context.Context) ([]ListStagesRow, error) {
	rows, err := q.db.Query(ctx, listStages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStagesRow{}
	for rows.Next() {
		var i ListStagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Manga,
			&i.Position,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagesByManga = `-- name: ListStagesByManga :many
SELECT id, manga, position, name FROM stages WHERE manga = $1 ORDER BY position, name
`

type ListStagesByMangaRow struct {
	ID       pgtype.UUID
	Manga    string
	Position int32
	Name     string
}

func (q *Queries) ListStagesByManga(ctx context.Context, manga string) ([]ListStagesByMangaRow, error) {
	rows, err := q.db.Query(ctx, listStagesByManga, manga)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStagesByMangaRow{}
	for rows.Next() {
		var i ListStagesByMangaRow
		if err := rows.Scan(
			&i.ID,
			&i.Manga,
			&i.Position,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStage = `-- name: UpsertStage :one
INSERT INTO stages (id, manga, position, name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
    SET manga      = EXCLUDED.manga,
        position   = EXCLUDED.position,
        name       = EXCLUDED.name,
        updated_at = now()
RETURNING id, manga, position, name
`

type UpsertStageParams struct {
	ID       pgtype.UUID
	Manga    string
	Position int32
	Name     string
}

type UpsertStageRow struct {
	ID       pgtype.UUID
	Manga    string
	Position int32
	Name     string
}

func (q *Queries) UpsertStage(ctx context.Context, arg UpsertStageParams) (UpsertStageRow, error) {
	row := q.db.QueryRow(ctx, upsertStage,
		arg.ID,
		arg.Manga,
		arg.Position,
		arg.Name,
	)
	var i UpsertStageRow
	err := row.Scan(
		&i.ID,
		&i.Manga,
		&i.Position,
		&i.Name,
	)
	return i, err
}
