// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stands.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePowerSkills = `-- name: DeletePowerSkills :exec
DELETE FROM power_skills WHERE power_id = $1
`

func (q *Queries) DeletePowerSkills(ctx context.Context, powerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePowerSkills, powerID)
	return err
}

const deleteStandByID = `-- name: DeleteStandByID :execrows
DELETE FROM powers WHERE id = $1 AND kind = 'STAND'
`

func (q *Queries) DeleteStandByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStandByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const filterStandRows = `-- name: FilterStandRows :many
WITH RECURSIVE base AS (SELECT p.id,
                                p.name,
                                p.description,
                                p.rarity,
                                p.picture,
                                p.picture_thumb,
                                p.picture_status,
                                s.attack_power,
                                s.speed,
                                s.attack_range,
                                s.endurance,
                                s."precision",
                                s.potential,
                                s.evolves_from_id,
                                true AS matched
                         FROM stands s
                                  JOIN powers p ON p.id = s.id
                                  LEFT JOIN stands ef ON ef.id = s.evolves_from_id
                                  LEFT JOIN powers efp ON efp.id = ef.id
                         WHERE ($1::power_rarity IS NULL OR p.rarity = $1::power_rarity)
                           AND ($2::stand_stat IS NULL OR
                                s.attack_power = $2::stand_stat)
                           AND ($3::stand_stat IS NULL OR s.speed = $3::stand_stat)
                           AND ($4::stand_stat IS NULL OR
                                s.attack_range = $4::stand_stat)
                           AND ($5::stand_stat IS NULL OR
                                s.endurance = $5::stand_stat)
                           AND ($6::stand_stat IS NULL OR
                                s."precision" = $6::stand_stat)
                           AND ($7::stand_stat IS NULL OR
                                s.potential = $7::stand_stat)
                           AND ($8::text IS NULL OR
                                efp.name = $8::text)),
     chain AS (SELECT id, name, description, rarity, picture, picture_thumb, picture_status, attack_power, speed, attack_range, endurance, precision, potential, evolves_from_id, matched
               FROM base
               UNION
               SELECT p2.id,
                      p2.name,
                      p2.description,
                      p2.rarity,
                      p2.picture,
                      p2.picture_thumb,
                      p2.picture_status,
                      s2.attack_power,
                      s2.speed,
                      s2.attack_range,
                      s2.endurance,
                      s2."precision",
                      s2.potential,
                      s2.evolves_from_id,
                      false AS matched
               FROM stands s2
                        JOIN powers p2 ON p2.id = s2.id
                        JOIN chain c ON c.evolves_from_id = s2.id),
     dedup AS (SELECT id,
                      name,
                      description,
                      rarity,
                      picture,
                      picture_thumb,
                      picture_status,
                      attack_power,
                      speed,
                      attack_range,
                      endurance,
                      "precision",
                      potential,
                      evolves_from_id,
                      bool_or(matched) AS matched
               FROM chain
               GROUP BY id, name, description, rarity, picture, picture_thumb, picture_status, attack_power, speed,
                        attack_range, endurance, "precision", potential, evolves_from_id)
SELECT d.id,
       d.name,
       d.description,
       d.rarity,
       d.picture,
       d.picture_thumb,
       d.picture_status,
       d.attack_power,
       d.speed,
       d.attack_range,
       d.endurance,
       d."precision",
       d.potential,
       d.evolves_from_id,
       d.matched,
       COALESCE(array_agg(ps.skill ORDER BY ps.position) FILTER (WHERE ps.skill IS NOT NULL), '{}')::text[] AS skills
FROM dedup d
         LEFT JOIN power_skills ps ON ps.power_id = d.id
GROUP BY d.id, d.name, d.description, d.rarity, d.picture, d.picture_thumb, d.picture_status, d.attack_power, d.speed,
         d.attack_range, d.endurance, d."precision", d.potential, d.evolves_from_id, d.matched
ORDER BY d.name
`

type FilterStandRowsParams struct {
	Rarity          *PowerRarity
	AttackPower     *StandStat
	Speed           *StandStat
	AttackRange     *StandStat
	Endurance       *StandStat
	Precision       *StandStat
	Potential       *StandStat
	EvolvesFromName *string
}

type FilterStandRowsRow struct {
	ID            pgtype.UUID
	Name          string
	Description   string
	Rarity        string
	Picture       string
	PictureThumb  string
	PictureStatus string
	AttackPower   string
	Speed         string
	AttackRange   string
	Endurance     string
	Precision     string
	Potential     string
	EvolvesFromID pgtype.UUID
	Matched       bool
	Skills        []string
}

// Returns every stand matching the (all-optional) filters, marked
// matched = true, plus their full ancestor chains (matched = false) needed
// to hydrate Stand.EvolvesFrom(...). Callers must drop matched = false rows
// from the final result set.
func (q *Queries) FilterStandRows(ctx context.Context, arg FilterStandRowsParams) ([]FilterStandRowsRow, error) {
	rows, err := q.db.Query(ctx, filterStandRows,
		arg.Rarity,
		arg.AttackPower,
		arg.Speed,
		arg.AttackRange,
		arg.Endurance,
		arg.Precision,
		arg.Potential,
		arg.EvolvesFromName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterStandRowsRow{}
	for rows.Next() {
		var i FilterStandRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Rarity,
			&i.Picture,
			&i.PictureThumb,
			&i.PictureStatus,
			&i.AttackPower,
			&i.Speed,
			&i.AttackRange,
			&i.Endurance,
			&i.Precision,
			&i.Potential,
			&i.EvolvesFromID,
			&i.Matched,
			&i.Skills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStandIDByName = `-- name: GetStandIDByName :one
SELECT p.id
FROM powers p
         JOIN stands s ON s.id = p.id
WHERE p.name = $1
`

func (q *Queries) GetStandIDByName(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getStandIDByName, name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getStandRowsByID = `-- name: GetStandRowsByID :many
WITH RECURSIVE chain AS (SELECT p.id,
                                 p.name,
                                 p.description,
                                 p.rarity,
                                 p.picture,
                                 p.picture_thumb,
                                 p.picture_status,
                                 s.attack_power,
                                 s.speed,
                                 s.attack_range,
                                 s.endurance,
                                 s."precision",
                                 s.potential,
                                 s.evolves_from_id,
                                 true AS matched
                          FROM stands s
                                   JOIN powers p ON p.id = s.id
                          WHERE p.id = $1
                          UNION
                          SELECT p2.id,
                                 p2.name,
                                 p2.description,
                                 p2.rarity,
                                 p2.picture,
                                 p2.picture_thumb,
                                 p2.picture_status,
                                 s2.attack_power,
                                 s2.speed,
                                 s2.attack_range,
                                 s2.endurance,
                                 s2."precision",
                                 s2.potential,
                                 s2.evolves_from_id,
                                 false AS matched
                          FROM stands s2
                                   JOIN powers p2 ON p2.id = s2.id
                                   JOIN chain c ON c.evolves_from_id = s2.id),
     dedup AS (SELECT id,
                      name,
                      description,
                      rarity,
                      picture,
                      picture_thumb,
                      picture_status,
                      attack_power,
                      speed,
                      attack_range,
                      endurance,
                      "precision",
                      potential,
                      evolves_from_id,
                      bool_or(matched) AS matched
               FROM chain
               GROUP BY id, name, description, rarity, picture, picture_thumb, picture_status, attack_power, speed,
                        attack_range, endurance, "precision", potential, evolves_from_id)
SELECT d.id,
       d.name,
       d.description,
       d.rarity,
       d.picture,
       d.picture_thumb,
       d.picture_status,
       d.attack_power,
       d.speed,
       d.attack_range,
       d.endurance,
       d."precision",
       d.potential,
       d.evolves_from_id,
       d.matched,
       COALESCE(array_agg(ps.skill ORDER BY ps.position) FILTER (WHERE ps.skill IS NOT NULL), '{}')::text[] AS skills
FROM dedup d
         LEFT JOIN power_skills ps ON ps.power_id = d.id
GROUP BY d.id, d.name, d.description, d.rarity, d.picture, d.picture_thumb, d.picture_status, d.attack_power, d.speed,
         d.attack_range, d.endurance, d."precision", d.potential, d.evolves_from_id, d.matched
ORDER BY d.name
`

type GetStandRowsByIDRow struct {
	ID            pgtype.UUID
	Name          string
	Description   string
	Rarity        string
	Picture       string
	PictureThumb  string
	PictureStatus string
	AttackPower   string
	Speed         string
	AttackRange   string
	Endurance     string
	Precision     string
	Potential     string
	EvolvesFromID pgtype.UUID
	Matched       bool
	Skills        []string
}

// Same shape as GetStandRowsByName, keyed by id instead of name.
func (q *Queries) GetStandRowsByID(ctx context.Context, id pgtype.UUID) ([]GetStandRowsByIDRow, error) {
	rows, err := q.db.Query(ctx, getStandRowsByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStandRowsByIDRow{}
	for rows.Next() {
		var i GetStandRowsByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Rarity,
			&i.Picture,
			&i.PictureThumb,
			&i.PictureStatus,
			&i.AttackPower,
			&i.Speed,
			&i.AttackRange,
			&i.Endurance,
			&i.Precision,
			&i.Potential,
			&i.EvolvesFromID,
			&i.Matched,
			&i.Skills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStandRowsByName = `-- name: GetStandRowsByName :many
WITH RECURSIVE chain AS (SELECT p.id,
                                 p.name,
                                 p.description,
                                 p.rarity,
                                 p.picture,
                                 p.picture_thumb,
                                 p.picture_status,
                                 s.attack_power,
                                 s.speed,
                                 s.attack_range,
                                 s.endurance,
                                 s."precision",
                                 s.potential,
                                 s.evolves_from_id,
                                 true AS matched
                          FROM stands s
                                   JOIN powers p ON p.id = s.id
                          WHERE p.name = $1
                          UNION
                          SELECT p2.id,
                                 p2.name,
                                 p2.description,
                                 p2.rarity,
                                 p2.picture,
                                 p2.picture_thumb,
                                 p2.picture_status,
                                 s2.attack_power,
                                 s2.speed,
                                 s2.attack_range,
                                 s2.endurance,
                                 s2."precision",
                                 s2.potential,
                                 s2.evolves_from_id,
                                 false AS matched
                          FROM stands s2
                                   JOIN powers p2 ON p2.id = s2.id
                                   JOIN chain c ON c.evolves_from_id = s2.id),
     dedup AS (SELECT id,
                      name,
                      description,
                      rarity,
                      picture,
                      picture_thumb,
                      picture_status,
                      attack_power,
                      speed,
                      attack_range,
                      endurance,
                      "precision",
                      potential,
                      evolves_from_id,
                      bool_or(matched) AS matched
               FROM chain
               GROUP BY id, name, description, rarity, picture, picture_thumb, picture_status, attack_power, speed,
                        attack_range, endurance, "precision", potential, evolves_from_id)
SELECT d.id,
       d.name,
       d.description,
       d.rarity,
       d.picture,
       d.picture_thumb,
       d.picture_status,
       d.attack_power,
       d.speed,
       d.attack_range,
       d.endurance,
       d."precision",
       d.potential,
       d.evolves_from_id,
       d.matched,
       COALESCE(array_agg(ps.skill ORDER BY ps.position) FILTER (WHERE ps.skill IS NOT NULL), '{}')::text[] AS skills
FROM dedup d
         LEFT JOIN power_skills ps ON ps.power_id = d.id
GROUP BY d.id, d.name, d.description, d.rarity, d.picture, d.picture_thumb, d.picture_status, d.attack_power, d.speed,
         d.attack_range, d.endurance, d."precision", d.potential, d.evolves_from_id, d.matched
ORDER BY d.name
`

type GetStandRowsByNameRow struct {
	ID            pgtype.UUID
	Name          string
	Description   string
	Rarity        string
	Picture       string
	PictureThumb  string
	PictureStatus string
	AttackPower   string
	Speed         string
	AttackRange   string
	Endurance     string
	Precision     string
	Potential     string
	EvolvesFromID pgtype.UUID
	Matched       bool
	Skills        []string
}

// Returns the stand matching `name` (matched = true) plus its full ancestor
// chain (matched = false), so the caller can hydrate Stand.EvolvesFrom(...)
// without extra round trips, then discard everything but the matched row.
func (q *Queries) GetStandRowsByName(ctx context.Context, name string) ([]GetStandRowsByNameRow, error) {
	rows, err := q.db.Query(ctx, getStandRowsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStandRowsByNameRow{}
	for rows.Next() {
		var i GetStandRowsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Rarity,
			&i.Picture,
			&i.PictureThumb,
			&i.PictureStatus,
			&i.AttackPower,
			&i.Speed,
			&i.AttackRange,
			&i.Endurance,
			&i.Precision,
			&i.Potential,
			&i.EvolvesFromID,
			&i.Matched,
			&i.Skills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPowerSkill = `-- name: InsertPowerSkill :exec
INSERT INTO power_skills (power_id, position, skill)
VALUES ($1, $2, $3)
`

type InsertPowerSkillParams struct {
	PowerID  pgtype.UUID
	Position int32
	Skill    string
}

func (q *Queries) InsertPowerSkill(ctx context.Context, arg InsertPowerSkillParams) error {
	_, err := q.db.Exec(ctx, insertPowerSkill, arg.PowerID, arg.Position, arg.Skill)
	return err
}

const listStandRows = `-- name: ListStandRows :many
SELECT p.id,
       p.name,
       p.description,
       p.rarity,
       p.picture,
       p.picture_thumb,
       p.picture_status,
       s.attack_power,
       s.speed,
       s.attack_range,
       s.endurance,
       s."precision",
       s.potential,
       s.evolves_from_id,
       true                                                                                            AS matched,
       COALESCE(array_agg(ps.skill ORDER BY ps.position) FILTER (WHERE ps.skill IS NOT NULL), '{}')::text[] AS skills
FROM stands s
         JOIN powers p ON p.id = s.id
         LEFT JOIN power_skills ps ON ps.power_id = p.id
GROUP BY p.id, p.name, p.description, p.rarity, p.picture, p.picture_thumb, p.picture_status, s.attack_power,
         s.speed, s.attack_range, s.endurance, s."precision", s.potential, s.evolves_from_id
ORDER BY p.name
`

type ListStandRowsRow struct {
	ID            pgtype.UUID
	Name          string
	Description   string
	Rarity        string
	Picture       string
	PictureThumb  string
	PictureStatus string
	AttackPower   string
	Speed         string
	AttackRange   string
	Endurance     string
	Precision     string
	Potential     string
	EvolvesFromID pgtype.UUID
	Matched       bool
	Skills        []string
}

// Returns every stand (matched = true always, no filter applied). Kept in
// the same shape as GetStandRowsByName/FilterStandRows so all three share
// one mapper.
func (q *Queries) ListStandRows(ctx context.Context) ([]ListStandRowsRow, error) {
	rows, err := q.db.Query(ctx, listStandRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStandRowsRow{}
	for rows.Next() {
		var i ListStandRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Rarity,
			&i.Picture,
			&i.PictureThumb,
			&i.PictureStatus,
			&i.AttackPower,
			&i.Speed,
			&i.AttackRange,
			&i.Endurance,
			&i.Precision,
			&i.Potential,
			&i.EvolvesFromID,
			&i.Matched,
			&i.Skills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePowerPicture = `-- name: UpdatePowerPicture :exec
UPDATE powers
SET picture        = COALESCE($1::text, picture),
    picture_thumb  = COALESCE($2::text, picture_thumb),
    picture_status = $3::picture_status,
    updated_at     = now()
WHERE id = $4
`

type UpdatePowerPictureParams struct {
	Picture       *string
	PictureThumb  *string
	PictureStatus string
	ID            pgtype.UUID
}

// Updates only a Power's picture renditions and pipeline status, without
// touching name/description/skills/stats - used by the PATCH .../picture
// handler (status -> PENDING) and by the background compression worker
// (status -> READY/FAILED). picture/picture_thumb are left untouched when
// NULL is passed, so the handler can move a row to PENDING without
// clobbering the renditions currently being served.
func (q *Queries) UpdatePowerPicture(ctx context.Context, arg UpdatePowerPictureParams) error {
	_, err := q.db.Exec(ctx, updatePowerPicture,
		arg.Picture,
		arg.PictureThumb,
		arg.PictureStatus,
		arg.ID,
	)
	return err
}

const upsertPower = `-- name: UpsertPower :one
INSERT INTO powers (id, kind, name, description, rarity, picture, picture_thumb, picture_status)
VALUES ($1, 'STAND', $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE
    SET name           = EXCLUDED.name,
        description    = EXCLUDED.description,
        rarity         = EXCLUDED.rarity,
        picture        = EXCLUDED.picture,
        picture_thumb  = EXCLUDED.picture_thumb,
        picture_status = EXCLUDED.picture_status,
        updated_at     = now()
RETURNING id
`

type UpsertPowerParams struct {
	ID            pgtype.UUID
	Name          string
	Description   string
	Rarity        string
	Picture       string
	PictureThumb  string
	PictureStatus string
}

func (q *Queries) UpsertPower(ctx context.Context, arg UpsertPowerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPower,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Rarity,
		arg.Picture,
		arg.PictureThumb,
		arg.PictureStatus,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertStand = `-- name: UpsertStand :exec
INSERT INTO stands (id, attack_power, speed, attack_range, endurance, "precision", potential, evolves_from_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
    SET attack_power    = EXCLUDED.attack_power,
        speed           = EXCLUDED.speed,
        attack_range    = EXCLUDED.attack_range,
        endurance       = EXCLUDED.endurance,
        "precision"     = EXCLUDED.precision,
        potential       = EXCLUDED.potential,
        evolves_from_id = EXCLUDED.evolves_from_id
`

type UpsertStandParams struct {
	ID            pgtype.UUID
	AttackPower   string
	Speed         string
	AttackRange   string
	Endurance     string
	Precision     string
	Potential     string
	EvolvesFromID pgtype.UUID
}

func (q *Queries) UpsertStand(ctx context.Context, arg UpsertStandParams) error {
	_, err := q.db.Exec(ctx, upsertStand,
		arg.ID,
		arg.AttackPower,
		arg.Speed,
		arg.AttackRange,
		arg.Endurance,
		arg.Precision,
		arg.Potential,
		arg.EvolvesFromID,
	)
	return err
}
