// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage_objects.sql

package db

import (
	"context"
)

const deleteStorageObjectsByProvider = `-- name: DeleteStorageObjectsByProvider :exec
DELETE FROM storage_objects
WHERE provider = $1
`

// Used by the reconciler to swap a provider's whole inventory in one
// transaction (see repositories.StorageLedger.Replace).
func (q *Queries) DeleteStorageObjectsByProvider(ctx context.Context, provider string) error {
	_, err := q.db.Exec(ctx, deleteStorageObjectsByProvider, provider)
	return err
}

const forgetStorageObject = `-- name: ForgetStorageObject :exec
DELETE FROM storage_objects
WHERE key = $1
`

func (q *Queries) ForgetStorageObject(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, forgetStorageObject, key)
	return err
}

const getStorageObject = `-- name: GetStorageObject :one
SELECT key, provider, bytes
FROM storage_objects
WHERE key = $1
`

type GetStorageObjectRow struct {
	Key      string
	Provider string
	Bytes    int64
}

func (q *Queries) GetStorageObject(ctx context.Context, key string) (GetStorageObjectRow, error) {
	row := q.db.QueryRow(ctx, getStorageObject, key)
	var i GetStorageObjectRow
	err := row.Scan(&i.Key, &i.Provider, &i.Bytes)
	return i, err
}

const listStorageObjectsByProvider = `-- name: ListStorageObjectsByProvider :many
SELECT key, provider, bytes
FROM storage_objects
WHERE provider = $1
`

type ListStorageObjectsByProviderRow struct {
	Key      string
	Provider string
	Bytes    int64
}

func (q *Queries) ListStorageObjectsByProvider(ctx context.Context, provider string) ([]ListStorageObjectsByProviderRow, error) {
	rows, err := q.db.Query(ctx, listStorageObjectsByProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStorageObjectsByProviderRow{}
	for rows.Next() {
		var i ListStorageObjectsByProviderRow
		if err := rows.Scan(&i.Key, &i.Provider, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordStorageObject = `-- name: RecordStorageObject :exec
INSERT INTO storage_objects (key, provider, bytes)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
    SET provider = EXCLUDED.provider,
        bytes    = EXCLUDED.bytes
`

type RecordStorageObjectParams struct {
	Key      string
	Provider string
	Bytes    int64
}

func (q *Queries) RecordStorageObject(ctx context.Context, arg RecordStorageObjectParams) error {
	_, err := q.db.Exec(ctx, recordStorageObject, arg.Key, arg.Provider, arg.Bytes)
	return err
}

const sumStorageUsage = `-- name: SumStorageUsage :many
SELECT provider, COALESCE(SUM(bytes), 0)::bigint AS bytes, count(*)::bigint AS objects
FROM storage_objects
GROUP BY provider
`

type SumStorageUsageRow struct {
	Provider string
	Bytes    int64
	Objects  int64
}

func (q *Queries) SumStorageUsage(ctx context.Context) ([]SumStorageUsageRow, error) {
	rows, err := q.db.Query(ctx, sumStorageUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumStorageUsageRow{}
	for rows.Next() {
		var i SumStorageUsageRow
		if err := rows.Scan(&i.Provider, &i.Bytes, &i.Objects); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
