// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, google_sub, email, username, complete_name, picture, role
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID
	GoogleSub    string
	Email        string
	Username     string
	CompleteName string
	Picture      string
	Role         string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Username,
		&i.CompleteName,
		&i.Picture,
		&i.Role,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, google_sub, email, username, complete_name, picture, role
FROM users
WHERE google_sub = $1
`

type GetUserByGoogleSubRow struct {
	ID           pgtype.UUID
	GoogleSub    string
	Email        string
	Username     string
	CompleteName string
	Picture      string
	Role         string
}

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub string) (GetUserByGoogleSubRow, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i GetUserByGoogleSubRow
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Username,
		&i.CompleteName,
		&i.Picture,
		&i.Role,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_sub, email, username, complete_name, picture, role
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           pgtype.UUID
	GoogleSub    string
	Email        string
	Username     string
	CompleteName string
	Picture      string
	Role         string
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Username,
		&i.CompleteName,
		&i.Picture,
		&i.Role,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, google_sub, email, username, complete_name, picture, role
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID           pgtype.UUID
	GoogleSub    string
	Email        string
	Username     string
	CompleteName string
	Picture      string
	Role         string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Username,
		&i.CompleteName,
		&i.Picture,
		&i.Role,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, google_sub, email, username, complete_name, picture, role)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE
    SET email         = EXCLUDED.email,
        username      = EXCLUDED.username,
        complete_name = EXCLUDED.complete_name,
        picture       = EXCLUDED.picture,
        role          = EXCLUDED.role,
        updated_at    = now()
RETURNING id
`

type UpsertUserParams struct {
	ID           pgtype.UUID
	GoogleSub    string
	Email        string
	Username     string
	CompleteName string
	Picture      string
	Role         string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.GoogleSub,
		arg.Email,
		arg.Username,
		arg.CompleteName,
		arg.Picture,
		arg.Role,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
