import { readFileSync, readdirSync, statSync } from 'fs'
import { join } from 'path'

import type { StandResponse } from '@/shared/contracts/dto'

// Compile-time half of the evolvesFrom-collapsed-to-any guard below: `any`
// is the only type where `0 extends 1 & T` is true, so this fails to
// typecheck (a literal type `true` can't hold `false`) the moment
// StandResponse degrades to `any` - independent of the runtime safeParse
// check, since a TS-level collapse produces no runtime symptom by itself.
type IsAny<T> = 0 extends 1 & T ? true : false
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const _evolvesFromIsNotAny: false = null as unknown as IsAny<StandResponse['evolvesFrom']>

// Guards the generated-contracts norm (ObsidianVault/contratos-tipos-
// generados.md): apps/backend/cmd/typegen is the only place a wire type
// (DTO/enum/WS payload) may be declared - everything under src/ either
// re-exports from '@/shared/contracts/*' or composes it. Follows
// copy.test.ts's walk/it.each pattern so a failure is labeled by file.
const SRC_ROOT = join(__dirname, '..', '..')
const CONTRACTS_DIR = join(SRC_ROOT, 'shared', 'contracts')

function listSourceFiles(dir: string, out: string[] = []) {
  for (const entry of readdirSync(dir)) {
    if (entry === 'node_modules' || entry === '__tests__') continue
    const full = join(dir, entry)
    const stats = statSync(full)
    if (stats.isDirectory()) {
      listSourceFiles(full, out)
    } else if (/\.(ts|tsx)$/.test(entry) && !/\.test\.[tj]sx?$/.test(entry)) {
      out.push(full)
    }
  }
  return out
}

function stripComments(source: string) {
  return source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '')
}

const allFiles = listSourceFiles(SRC_ROOT)
const nonGeneratedFiles = allFiles.filter((f) => !f.startsWith(CONTRACTS_DIR + require('path').sep))
const generatedFiles = allFiles.filter((f) => f.startsWith(CONTRACTS_DIR + require('path').sep))

describe('generated contracts: no hand-written wire type re-declares one', () => {
  // A wire-shaped type name declared outside contracts/ - StandResponse,
  // GameConfigRequest, etc. Deliberately narrow (Response/Request/Payload/
  // Snapshot/Input suffix), which still catches a client-only type that
  // happens to end the same way (UseMatchHotkeysInput, CachedResponse) -
  // those are allowlisted below by path rather than tightened further,
  // since a name-based heuristic can't tell "wire shape" from "coincidence"
  // any more precisely without false negatives creeping back in.
  const WIRE_TYPE_DECL = /^\s*(export\s+)?type\s+\w*(Response|Request|Payload|Snapshot|Input)\s*=\s*\{/m
  const ENUM_DECL = /z\.enum\(\s*\[/
  const ALLOWLIST = [
    join('features', 'game', 'hooks', 'use-match-hotkeys.ts'),
    join('features', 'game', 'lib', 'hotkeys.ts'),
    join('shared', 'api', 'etag.ts'),
  ]

  it.each(
    nonGeneratedFiles
      .filter((f) => !ALLOWLIST.some((a) => f.endsWith(a)))
      .map((f) => [f.replace(SRC_ROOT, ''), f])
  )('%s', (_label, file) => {
    const code = stripComments(readFileSync(file as string, 'utf8'))
    expect(WIRE_TYPE_DECL.test(code)).toBe(false)
    expect(ENUM_DECL.test(code)).toBe(false)
  })
})

describe('generated contracts: deleted hand-mirror modules stay deleted', () => {
  const BANNED_SPECIFIERS = ["'@/shared/lib/zod'", "'@/shared/types/api'", "'@/features/game/types/game-ws.types'"]

  it.each(nonGeneratedFiles.map((f) => [f.replace(SRC_ROOT, ''), f]))('%s', (_label, file) => {
    const code = readFileSync(file as string, 'utf8')
    for (const specifier of BANNED_SPECIFIERS) {
      expect(code.includes(specifier)).toBe(false)
    }
  })
})

describe('generated contracts: every file under contracts/ is marked and un-split', () => {
  const HEADER = '// Code generated by cmd/typegen. DO NOT EDIT.'
  // tsconfig's moduleSuffixes (['.web', '.native', '']) means a *.web.ts or
  // *.native.ts file would silently SHADOW its plain counterpart on that
  // platform only - both would typecheck fine, giving web and native
  // genuinely different contracts with no error anywhere. typegen never
  // emits these; a match here means one was hand-added.
  const PLATFORM_SPLIT = /\.(web|native)\.tsx?$/

  it.each(generatedFiles.map((f) => [f.replace(SRC_ROOT, ''), f]))('%s', (_label, file) => {
    expect(PLATFORM_SPLIT.test(file)).toBe(false)
    expect(readFileSync(file as string, 'utf8').startsWith(HEADER)).toBe(true)
  })
})

describe('generated contracts: every error code has an i18n key', () => {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { errorCodeSchema } = require('@/shared/contracts/errors') as typeof import('@/shared/contracts/errors')
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const enGB = require('@/shared/i18n/locales/en-GB.json') as { errors: Record<string, string> }

  it.each(errorCodeSchema.options.map((code) => [code, code]))(
    'errors.%s exists in en-GB.json',
    (_label, code) => {
      expect(enGB.errors[code as string]).toEqual(expect.any(String))
    }
  )
})

describe('generated contracts: SUPPORTED_LOCALES matches the generated Locale enum', () => {
  it('is exactly localeSchema.options, in the same order', () => {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { localeSchema } = require('@/shared/contracts/enums') as typeof import('@/shared/contracts/enums')
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { SUPPORTED_LOCALES } = require('@/shared/i18n') as typeof import('@/shared/i18n')
    expect(SUPPORTED_LOCALES).toEqual(localeSchema.options)
  })
})

describe('generated contracts: StandResponse.evolvesFrom did not collapse to any', () => {
  // z.lazy() without the z.ZodType<X> annotation on standResponseSchema
  // (emit.go's emitRecursiveStruct) makes z.infer collapse the WHOLE
  // StandResponse type to `any` - tsc reports nothing, since `any` is
  // assignable to everything, so this can't be caught as a type error
  // anywhere a StandResponse is merely assigned. It CAN be caught by
  // trying to assign something that is only valid if the type is real -
  // here, a string where evolvesFrom is required, which `any` would accept
  // but a real recursive type never would.
  it('rejects a string in place of evolvesFrom', () => {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { standResponseSchema } = require('@/shared/contracts/dto') as typeof import('@/shared/contracts/dto')
    const bad = {
      id: '1',
      name: 'n',
      description: 'd',
      rarity: 'COMMON',
      skills: [],
      picture: '',
      pictureThumb: '',
      pictureStatus: 'NONE',
      attackPower: 'E',
      speed: 'E',
      attackRange: 'E',
      endurance: 'E',
      precision: 'E',
      potential: 'E',
      evolvesFrom: 'not-an-object-or-null',
    }
    expect(standResponseSchema.safeParse(bad).success).toBe(false)
  })
})
