// Code generated by cmd/typegen. DO NOT EDIT.
//
// Source of truth: apps/backend/internal/infrastructure/api/dto and
// apps/backend/internal/domain/enums. Regenerate with `make types` from
// apps/backend (or `make types-docker`). CI fails if this file is stale.

import { z } from 'zod'
import { AbilitySource, FruitMastery, FruitType, GameModeKind, GameState, HakiLevel, HamonLevel, LobbyVisibility, Locale, Manga, ParticipantKind, PhysicalForm, PictureStatus, PictureSubjectKind, PowerRarity, RevealSpeed, SpinLevel, StandStat, UserRole, abilitySourceSchema, fruitMasterySchema, fruitTypeSchema, gameModeKindSchema, gameStateSchema, hakiLevelSchema, hamonLevelSchema, lobbyVisibilitySchema, localeSchema, mangaSchema, participantKindSchema, physicalFormSchema, pictureStatusSchema, pictureSubjectKindSchema, powerRaritySchema, revealSpeedSchema, spinLevelSchema, standStatSchema, userRoleSchema } from './enums'

export const adminUpdateUserRequestSchema = z.object({
  username: z.string(),
})
export type AdminUpdateUserRequest = z.infer<typeof adminUpdateUserRequestSchema>

export const devilFruitResponseSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  rarity: powerRaritySchema,
  skills: z.array(z.string()),
  picture: z.string(),
  pictureThumb: z.string(),
  pictureStatus: pictureStatusSchema,
  fruitType: fruitTypeSchema,
})
export type DevilFruitResponse = z.infer<typeof devilFruitResponseSchema>

export const gameRoundResultResponseSchema = z.object({
  winner: z.string(),
  decidedByCoinFlip: z.boolean(),
})
export type GameRoundResultResponse = z.infer<typeof gameRoundResultResponseSchema>

export const gameStageResponseSchema = z.object({
  id: z.string(),
  manga: mangaSchema,
  order: z.number().int(),
  name: z.string(),
  description: z.string(),
  picture: z.string(),
  pictureThumb: z.string(),
  pictureStatus: pictureStatusSchema,
})
export type GameStageResponse = z.infer<typeof gameStageResponseSchema>

export const gameRoundResponseSchema = z.object({
  index: z.number().int(),
  stage: gameStageResponseSchema,
  options: z.array(z.string()),
  tiebreakUsed: z.boolean(),
  votedParticipantIds: z.array(z.string()),
  votes: z.record(z.string(), z.string()).optional(),
  tiedVotes: z.record(z.string(), z.string()).optional(),
  result: gameRoundResultResponseSchema.optional(),
})
export type GameRoundResponse = z.infer<typeof gameRoundResponseSchema>

export const gameTeamResponseSchema = z.object({
  id: z.string(),
  name: z.string(),
  color: z.number().int().nonnegative(),
  memberIds: z.array(z.string()),
})
export type GameTeamResponse = z.infer<typeof gameTeamResponseSchema>

export const gameViewerResponseSchema = z.object({
  participantId: z.string(),
  teamId: z.string(),
  isHost: z.boolean(),
  hasVoted: z.boolean(),
  vote: z.string().optional(),
})
export type GameViewerResponse = z.infer<typeof gameViewerResponseSchema>

export const googleLoginRequestSchema = z.object({
  idToken: z.string(),
})
export type GoogleLoginRequest = z.infer<typeof googleLoginRequestSchema>

export const joinGameRequestSchema = z.object({
  code: z.string(),
})
export type JoinGameRequest = z.infer<typeof joinGameRequestSchema>

export const lobbyPreviewResponseSchema = z.object({
  gameId: z.string(),
  mode: gameModeKindSchema,
  hostDisplayName: z.string(),
  abilitySource: abilitySourceSchema,
  mangas: z.array(mangaSchema),
  playerCount: z.number().int(),
  maxPlayers: z.number().int(),
  votingWindowSeconds: z.number().int(),
  allowBots: z.boolean(),
  locked: z.boolean(),
  code: z.string(),
  visibility: lobbyVisibilitySchema,
})
export type LobbyPreviewResponse = z.infer<typeof lobbyPreviewResponseSchema>

export const participantOutcomeResponseSchema = z.object({
  participantId: z.string(),
  displayName: z.string(),
  teamId: z.string(),
  bot: z.boolean(),
})
export type ParticipantOutcomeResponse = z.infer<typeof participantOutcomeResponseSchema>

export const gameResultResponseSchema = z.object({
  mode: gameModeKindSchema,
  winner: z.string(),
  participants: z.array(participantOutcomeResponseSchema).optional(),
  roundsPlayed: z.number().int(),
  aborted: z.boolean(),
})
export type GameResultResponse = z.infer<typeof gameResultResponseSchema>

export const pictureEventPayloadSchema = z.object({
  kind: pictureSubjectKindSchema,
  subjectId: z.string(),
  status: pictureStatusSchema,
})
export type PictureEventPayload = z.infer<typeof pictureEventPayloadSchema>

export const poolFilterPayloadSchema = z.object({
  standRarities: z.array(powerRaritySchema).optional(),
  fruitRarities: z.array(powerRaritySchema).optional(),
  fruitTypes: z.array(fruitTypeSchema).optional(),
  banned: z.array(z.string()).optional(),
})
export type PoolFilterPayload = z.infer<typeof poolFilterPayloadSchema>

export const createGameRequestSchema = z.object({
  mode: gameModeKindSchema,
  stageMangas: z.array(mangaSchema),
  powerMangas: z.array(mangaSchema),
  abilitySource: abilitySourceSchema,
  teamSize: z.number().int(),
  allowBots: z.boolean(),
  visibility: lobbyVisibilitySchema.optional(),
  votingWindowSeconds: z.number().int().optional(),
  poolFilter: poolFilterPayloadSchema.optional(),
  revealSpeed: revealSpeedSchema.optional(),
  summaryDurationSeconds: z.number().int().optional(),
})
export type CreateGameRequest = z.infer<typeof createGameRequestSchema>

export const poolFilterResponseSchema = z.object({
  standRarities: z.array(powerRaritySchema),
  fruitRarities: z.array(powerRaritySchema),
  fruitTypes: z.array(fruitTypeSchema),
  banned: z.array(z.string()),
})
export type PoolFilterResponse = z.infer<typeof poolFilterResponseSchema>

export const gameConfigResponseSchema = z.object({
  stageMangas: z.array(mangaSchema),
  powerMangas: z.array(mangaSchema),
  abilitySource: abilitySourceSchema,
  teamSize: z.number().int(),
  allowBots: z.boolean(),
  visibility: lobbyVisibilitySchema,
  votingWindowSeconds: z.number().int(),
  poolFilter: poolFilterResponseSchema,
  revealSpeed: revealSpeedSchema,
  summaryDurationSeconds: z.number().int(),
})
export type GameConfigResponse = z.infer<typeof gameConfigResponseSchema>

export const publicLobbyResponseSchema = z.object({
  gameId: z.string(),
  mode: gameModeKindSchema,
  hostDisplayName: z.string(),
  abilitySource: abilitySourceSchema,
  mangas: z.array(mangaSchema),
  playerCount: z.number().int(),
  maxPlayers: z.number().int(),
  votingWindowSeconds: z.number().int(),
  allowBots: z.boolean(),
  locked: z.boolean(),
})
export type PublicLobbyResponse = z.infer<typeof publicLobbyResponseSchema>

export const publicLobbyListResponseSchema = z.object({
  items: z.array(publicLobbyResponseSchema),
})
export type PublicLobbyListResponse = z.infer<typeof publicLobbyListResponseSchema>

export const publicUserResponseSchema = z.object({
  id: z.string(),
  username: z.string(),
  completeName: z.string(),
  avatar: z.string(),
  avatarThumb: z.string(),
})
export type PublicUserResponse = z.infer<typeof publicUserResponseSchema>

export const stageResponseSchema = z.object({
  id: z.string(),
  manga: mangaSchema,
  order: z.number().int(),
  name: z.string(),
  description: z.string(),
  picture: z.string(),
  pictureThumb: z.string(),
  pictureStatus: pictureStatusSchema,
})
export type StageResponse = z.infer<typeof stageResponseSchema>

export const stageTranslationRequestSchema = z.object({
  description: z.string(),
})
export type StageTranslationRequest = z.infer<typeof stageTranslationRequestSchema>

export const stageRequestSchema = z.object({
  manga: mangaSchema,
  order: z.number().int(),
  name: z.string(),
  translations: z.partialRecord(localeSchema, stageTranslationRequestSchema),
})
export type StageRequest = z.infer<typeof stageRequestSchema>

export const stageTranslationResponseSchema = z.object({
  description: z.string(),
})
export type StageTranslationResponse = z.infer<typeof stageTranslationResponseSchema>

export const stageTranslationsResponseSchema = z.object({
  translations: z.partialRecord(localeSchema, stageTranslationResponseSchema),
})
export type StageTranslationsResponse = z.infer<typeof stageTranslationsResponseSchema>

export type StandResponse = {
  id: string
  name: string
  description: string
  rarity: PowerRarity
  skills: string[]
  picture: string
  pictureThumb: string
  pictureStatus: PictureStatus
  attackPower: StandStat
  speed: StandStat
  attackRange: StandStat
  endurance: StandStat
  precision: StandStat
  potential: StandStat
  evolvesFrom: StandResponse | null
}
export const standResponseSchema: z.ZodType<StandResponse> = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  rarity: powerRaritySchema,
  skills: z.array(z.string()),
  picture: z.string(),
  pictureThumb: z.string(),
  pictureStatus: pictureStatusSchema,
  attackPower: standStatSchema,
  speed: standStatSchema,
  attackRange: standStatSchema,
  endurance: standStatSchema,
  precision: standStatSchema,
  potential: standStatSchema,
  evolvesFrom: z.lazy(() => standResponseSchema).nullable(),
})

export const gameLoadoutResponseSchema = z.object({
  stand: standResponseSchema.optional(),
  devilFruit: devilFruitResponseSchema.optional(),
  spin: spinLevelSchema,
  hamon: hamonLevelSchema,
  fruitMastery: fruitMasterySchema,
  armamentHaki: hakiLevelSchema,
  observationHaki: hakiLevelSchema,
  conquerorHaki: hakiLevelSchema,
  physicalForm: physicalFormSchema,
})
export type GameLoadoutResponse = z.infer<typeof gameLoadoutResponseSchema>

export const gameParticipantResponseSchema = z.object({
  id: z.string(),
  userId: z.string().optional(),
  displayName: z.string(),
  teamId: z.string(),
  kind: participantKindSchema,
  connected: z.boolean(),
  avatarThumb: z.string(),
  loadout: gameLoadoutResponseSchema.optional(),
})
export type GameParticipantResponse = z.infer<typeof gameParticipantResponseSchema>

export const gameSnapshotResponseSchema = z.object({
  id: z.string(),
  code: z.string(),
  state: gameStateSchema,
  mode: gameModeKindSchema,
  hostId: z.string(),
  locked: z.boolean(),
  config: gameConfigResponseSchema,
  teams: z.array(gameTeamResponseSchema),
  participants: z.array(gameParticipantResponseSchema),
  rounds: z.array(gameRoundResponseSchema),
  result: gameResultResponseSchema.optional(),
  revealEndsAt: z.iso.datetime({ offset: true }).optional(),
  votingEndsAt: z.iso.datetime({ offset: true }).optional(),
  resultEndsAt: z.iso.datetime({ offset: true }).optional(),
  summaryEndsAt: z.iso.datetime({ offset: true }).optional(),
})
export type GameSnapshotResponse = z.infer<typeof gameSnapshotResponseSchema>

export const gameStateResponseSchema = z.object({
  game: gameSnapshotResponseSchema,
  you: gameViewerResponseSchema,
})
export type GameStateResponse = z.infer<typeof gameStateResponseSchema>

export const streamTicketResponseSchema = z.object({
  ticket: z.string(),
  expiresAt: z.iso.datetime({ offset: true }),
})
export type StreamTicketResponse = z.infer<typeof streamTicketResponseSchema>

export const translationRequestSchema = z.object({
  description: z.string(),
  skills: z.array(z.string()),
})
export type TranslationRequest = z.infer<typeof translationRequestSchema>

export const devilFruitRequestSchema = z.object({
  name: z.string(),
  translations: z.partialRecord(localeSchema, translationRequestSchema),
  rarity: powerRaritySchema,
  fruitType: fruitTypeSchema,
})
export type DevilFruitRequest = z.infer<typeof devilFruitRequestSchema>

export const standRequestSchema = z.object({
  name: z.string(),
  translations: z.partialRecord(localeSchema, translationRequestSchema),
  rarity: powerRaritySchema,
  attackPower: standStatSchema,
  speed: standStatSchema,
  attackRange: standStatSchema,
  endurance: standStatSchema,
  precision: standStatSchema,
  potential: standStatSchema,
  evolvesFromId: z.string().optional(),
})
export type StandRequest = z.infer<typeof standRequestSchema>

export const translationResponseSchema = z.object({
  description: z.string(),
  skills: z.array(z.string()),
})
export type TranslationResponse = z.infer<typeof translationResponseSchema>

export const powerTranslationsResponseSchema = z.object({
  translations: z.partialRecord(localeSchema, translationResponseSchema),
})
export type PowerTranslationsResponse = z.infer<typeof powerTranslationsResponseSchema>

export const updateConfigPayloadSchema = z.object({
  mode: gameModeKindSchema,
  stageMangas: z.array(mangaSchema),
  powerMangas: z.array(mangaSchema),
  abilitySource: abilitySourceSchema,
  teamSize: z.number().int(),
  allowBots: z.boolean(),
  visibility: lobbyVisibilitySchema,
  votingWindowSeconds: z.number().int(),
  poolFilter: poolFilterPayloadSchema.optional(),
  revealSpeed: revealSpeedSchema.optional(),
  summaryDurationSeconds: z.number().int().optional(),
})
export type UpdateConfigPayload = z.infer<typeof updateConfigPayloadSchema>

export const updateProfileRequestSchema = z.object({
  username: z.string(),
  language: localeSchema.optional(),
})
export type UpdateProfileRequest = z.infer<typeof updateProfileRequestSchema>

export const updateRoleRequestSchema = z.object({
  role: userRoleSchema,
})
export type UpdateRoleRequest = z.infer<typeof updateRoleRequestSchema>

export const userResponseSchema = z.object({
  id: z.string(),
  email: z.string(),
  username: z.string(),
  completeName: z.string(),
  avatar: z.string(),
  avatarThumb: z.string(),
  avatarStatus: pictureStatusSchema,
  role: userRoleSchema,
  language: localeSchema,
})
export type UserResponse = z.infer<typeof userResponseSchema>

export const loginResponseSchema = z.object({
  accessToken: z.string(),
  tokenType: z.string(),
  expiresAt: z.iso.datetime({ offset: true }),
  user: userResponseSchema,
})
export type LoginResponse = z.infer<typeof loginResponseSchema>

