// Code generated by cmd/typegen. DO NOT EDIT.
//
// Source of truth: apps/backend/internal/infrastructure/api/dto and
// apps/backend/internal/domain/enums. Regenerate with `make types` from
// apps/backend (or `make types-docker`). CI fails if this file is stale.

import { z } from 'zod'

export const abilitySourceSchema = z.enum(['RANDOM', 'INVENTORY'])
export type AbilitySource = z.infer<typeof abilitySourceSchema>

export const fruitMasterySchema = z.enum(['NONE', 'REGULAR', 'ADVANCED', 'AWAKENED'])
export type FruitMastery = z.infer<typeof fruitMasterySchema>

export const fruitTypeSchema = z.enum([
  'PARAMECIA',
  'ZOAN',
  'LOGIA',
  'SPECIAL_PARAMECIA',
  'ANCIENT_ZOAN',
  'MYTHICAL_ZOAN',
])
export type FruitType = z.infer<typeof fruitTypeSchema>

export const gameModeKindSchema = z.enum(['GAUNTLET', 'VERSUS'])
export type GameModeKind = z.infer<typeof gameModeKindSchema>

export const gameStateSchema = z.enum([
  'LOBBY',
  'ASSIGNING',
  'SUMMARY',
  'VOTING',
  'TIEBREAK',
  'RESOLVING',
  'FINISHED',
  'ABORTED',
])
export type GameState = z.infer<typeof gameStateSchema>

export const hakiLevelSchema = z.enum([
  'NONE',
  'PRIVATE',
  'VICE_ADMIRAL',
  'YONKO_COMMANDER',
  'YONKO_PLUS',
])
export type HakiLevel = z.infer<typeof hakiLevelSchema>

export const hamonLevelSchema = z.enum(['NONE', 'BASIC', 'ADVANCED', 'PERFECT'])
export type HamonLevel = z.infer<typeof hamonLevelSchema>

export const lobbyVisibilitySchema = z.enum(['PRIVATE', 'PUBLIC'])
export type LobbyVisibility = z.infer<typeof lobbyVisibilitySchema>

export const localeSchema = z.enum(['en-GB', 'es-ES', 'ca-ES'])
export type Locale = z.infer<typeof localeSchema>

export const mangaSchema = z.enum(['JOJO', 'ONE_PIECE'])
export type Manga = z.infer<typeof mangaSchema>

export const participantKindSchema = z.enum(['HUMAN', 'BOT'])
export type ParticipantKind = z.infer<typeof participantKindSchema>

export const physicalFormSchema = z.enum([
  'PRIVATE',
  'STRONG_FISHMAN',
  'MARINE_CAPTAIN',
  'VICE_ADMIRAL',
  'YONKO_COMMANDER',
  'YONKO_PLUS',
])
export type PhysicalForm = z.infer<typeof physicalFormSchema>

export const pictureStatusSchema = z.enum(['NONE', 'PENDING', 'READY', 'FAILED'])
export type PictureStatus = z.infer<typeof pictureStatusSchema>

export const pictureSubjectKindSchema = z.enum(['STAND', 'DEVIL_FRUIT', 'USER', 'STAGE'])
export type PictureSubjectKind = z.infer<typeof pictureSubjectKindSchema>

export const powerKindSchema = z.enum(['STAND', 'DEVIL_FRUIT'])
export type PowerKind = z.infer<typeof powerKindSchema>

export const powerRaritySchema = z.enum([
  'COMMON',
  'RARE',
  'EPIC',
  'LEGENDARY',
  'MYTHICAL',
])
export type PowerRarity = z.infer<typeof powerRaritySchema>

export const powerTraitSchema = z.enum(['REQUIRES_SPIN_4'])
export type PowerTrait = z.infer<typeof powerTraitSchema>

export const revealSpeedSchema = z.enum(['NORMAL', 'RELAXED', 'SWIFT'])
export type RevealSpeed = z.infer<typeof revealSpeedSchema>

export const spinLevelSchema = z.enum(['NONE', 'BASIC', 'GOLDEN', 'INFINITE'])
export type SpinLevel = z.infer<typeof spinLevelSchema>

export const squadVerdictSchema = z.enum(['SURVIVE', 'FALL'])
export type SquadVerdict = z.infer<typeof squadVerdictSchema>

export const standStatSchema = z.enum([
  'E',
  'D',
  'C',
  'B',
  'A',
  'INFINITE',
  'NULL',
])
export type StandStat = z.infer<typeof standStatSchema>

export const userRoleSchema = z.enum(['REGULAR', 'ADMIN'])
export type UserRole = z.infer<typeof userRoleSchema>

// Legacy aliases: existing call sites import these names. Generated from
// cmd/typegen's enumAliases table - delete an entry once its importers
// migrate to the canonical name above.
export const raritySchema = powerRaritySchema
export type Rarity = PowerRarity
export const roleSchema = userRoleSchema
export type Role = UserRole
export const gameModeSchema = gameModeKindSchema
export type GameMode = GameModeKind
