// Code generated by cmd/typegen. DO NOT EDIT.
//
// Source of truth: game.BuildManualRules (apps/backend/internal/domain/entities/game/
// manual_rules.go), computed from the same rule tables and effect resolver the
// game runs. The in-game manual renders this file, so it cannot drift from the
// code. Regenerate with `make types` from apps/backend (or
// `make types-docker`). CI fails if this file is stale.

export const MANUAL_RULES = {
  "tieRule": "FURTHEST_EVOLVED",
  "evolutions": [
    {
      "kind": "STAND",
      "driver": "SPIN",
      "stages": [
        {
          "name": "Tusk: Act 1",
          "tier": "BASIC"
        },
        {
          "name": "Tusk: Act 2",
          "tier": "GOLDEN"
        },
        {
          "name": "Tusk: Act 3",
          "tier": "GOLDEN"
        },
        {
          "name": "Tusk: Act 4",
          "tier": "INFINITE"
        }
      ],
      "levels": [
        "NONE",
        "BASIC",
        "GOLDEN",
        "INFINITE"
      ],
      "rows": [
        {
          "drawn": "Tusk: Act 1",
          "outcomes": [
            {
              "level": "NONE",
              "power": "Tusk: Act 1",
              "levelAfter": "BASIC",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "BASIC",
              "power": "Tusk: Act 1",
              "levelAfter": "BASIC",
              "change": "NONE"
            },
            {
              "level": "GOLDEN",
              "power": "Tusk: Act 3",
              "levelAfter": "GOLDEN",
              "change": "EVOLVED"
            },
            {
              "level": "INFINITE",
              "power": "Tusk: Act 4",
              "levelAfter": "INFINITE",
              "change": "EVOLVED"
            }
          ]
        },
        {
          "drawn": "Tusk: Act 2",
          "outcomes": [
            {
              "level": "NONE",
              "power": "Tusk: Act 2",
              "levelAfter": "GOLDEN",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "BASIC",
              "power": "Tusk: Act 2",
              "levelAfter": "GOLDEN",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "GOLDEN",
              "power": "Tusk: Act 2",
              "levelAfter": "GOLDEN",
              "change": "NONE"
            },
            {
              "level": "INFINITE",
              "power": "Tusk: Act 4",
              "levelAfter": "INFINITE",
              "change": "EVOLVED"
            }
          ]
        },
        {
          "drawn": "Tusk: Act 3",
          "outcomes": [
            {
              "level": "NONE",
              "power": "Tusk: Act 3",
              "levelAfter": "GOLDEN",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "BASIC",
              "power": "Tusk: Act 3",
              "levelAfter": "GOLDEN",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "GOLDEN",
              "power": "Tusk: Act 3",
              "levelAfter": "GOLDEN",
              "change": "NONE"
            },
            {
              "level": "INFINITE",
              "power": "Tusk: Act 4",
              "levelAfter": "INFINITE",
              "change": "EVOLVED"
            }
          ]
        },
        {
          "drawn": "Tusk: Act 4",
          "outcomes": [
            {
              "level": "NONE",
              "power": "Tusk: Act 4",
              "levelAfter": "INFINITE",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "BASIC",
              "power": "Tusk: Act 4",
              "levelAfter": "INFINITE",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "GOLDEN",
              "power": "Tusk: Act 4",
              "levelAfter": "INFINITE",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "INFINITE",
              "power": "Tusk: Act 4",
              "levelAfter": "INFINITE",
              "change": "NONE"
            }
          ]
        }
      ]
    },
    {
      "kind": "STAND",
      "driver": "SPIN",
      "stages": [
        {
          "name": "Soft \u0026 Wet"
        },
        {
          "name": "Soft \u0026 Wet: Go Beyond",
          "tier": "INFINITE"
        }
      ],
      "levels": [
        "NONE",
        "BASIC",
        "GOLDEN",
        "INFINITE"
      ],
      "rows": [
        {
          "drawn": "Soft \u0026 Wet",
          "outcomes": [
            {
              "level": "NONE",
              "power": "Soft \u0026 Wet",
              "levelAfter": "NONE",
              "change": "NONE"
            },
            {
              "level": "BASIC",
              "power": "Soft \u0026 Wet",
              "levelAfter": "BASIC",
              "change": "NONE"
            },
            {
              "level": "GOLDEN",
              "power": "Soft \u0026 Wet",
              "levelAfter": "GOLDEN",
              "change": "NONE"
            },
            {
              "level": "INFINITE",
              "power": "Soft \u0026 Wet: Go Beyond",
              "levelAfter": "INFINITE",
              "change": "EVOLVED"
            }
          ]
        },
        {
          "drawn": "Soft \u0026 Wet: Go Beyond",
          "outcomes": [
            {
              "level": "NONE",
              "power": "Soft \u0026 Wet: Go Beyond",
              "levelAfter": "INFINITE",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "BASIC",
              "power": "Soft \u0026 Wet: Go Beyond",
              "levelAfter": "INFINITE",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "GOLDEN",
              "power": "Soft \u0026 Wet: Go Beyond",
              "levelAfter": "INFINITE",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "INFINITE",
              "power": "Soft \u0026 Wet: Go Beyond",
              "levelAfter": "INFINITE",
              "change": "NONE"
            }
          ]
        }
      ]
    },
    {
      "kind": "STAND",
      "driver": "SPIN",
      "stages": [
        {
          "name": "Ball Breaker",
          "tier": "INFINITE"
        }
      ],
      "levels": [
        "NONE",
        "BASIC",
        "GOLDEN",
        "INFINITE"
      ],
      "rows": [
        {
          "drawn": "Ball Breaker",
          "outcomes": [
            {
              "level": "NONE",
              "power": "Ball Breaker",
              "levelAfter": "INFINITE",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "BASIC",
              "power": "Ball Breaker",
              "levelAfter": "INFINITE",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "GOLDEN",
              "power": "Ball Breaker",
              "levelAfter": "INFINITE",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "INFINITE",
              "power": "Ball Breaker",
              "levelAfter": "INFINITE",
              "change": "NONE"
            }
          ]
        }
      ]
    },
    {
      "kind": "DEVIL_FRUIT",
      "driver": "FRUIT_MASTERY",
      "stages": [
        {
          "name": "Gomu Gomu no mi"
        },
        {
          "name": "Hito Hito no mi: Model Nika",
          "tier": "AWAKENED"
        }
      ],
      "levels": [
        "REGULAR",
        "ADVANCED",
        "AWAKENED"
      ],
      "rows": [
        {
          "drawn": "Gomu Gomu no mi",
          "outcomes": [
            {
              "level": "REGULAR",
              "power": "Gomu Gomu no mi",
              "levelAfter": "REGULAR",
              "change": "NONE"
            },
            {
              "level": "ADVANCED",
              "power": "Gomu Gomu no mi",
              "levelAfter": "ADVANCED",
              "change": "NONE"
            },
            {
              "level": "AWAKENED",
              "power": "Hito Hito no mi: Model Nika",
              "levelAfter": "AWAKENED",
              "change": "EVOLVED"
            }
          ]
        },
        {
          "drawn": "Hito Hito no mi: Model Nika",
          "outcomes": [
            {
              "level": "REGULAR",
              "power": "Hito Hito no mi: Model Nika",
              "levelAfter": "AWAKENED",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "ADVANCED",
              "power": "Hito Hito no mi: Model Nika",
              "levelAfter": "AWAKENED",
              "change": "LEVEL_RAISED"
            },
            {
              "level": "AWAKENED",
              "power": "Hito Hito no mi: Model Nika",
              "levelAfter": "AWAKENED",
              "change": "NONE"
            }
          ]
        }
      ]
    }
  ],
  "statFloors": [
    {
      "cross": false,
      "causeSlot": "STAND",
      "when": {
        "kind": "POWERS",
        "names": [
          "Hermit Purple"
        ]
      },
      "target": "HAMON",
      "floor": "BASIC"
    },
    {
      "cross": true,
      "causeSlot": "STAND",
      "when": {
        "kind": "POWERS",
        "names": [
          "King Crimson"
        ]
      },
      "target": "OBSERVATION_HAKI",
      "floor": "YONKO_PLUS"
    },
    {
      "cross": false,
      "causeSlot": "DEVIL_FRUIT",
      "when": {
        "kind": "FRUIT_TYPE",
        "fruitTypes": [
          "MYTHICAL_ZOAN",
          "ANCIENT_ZOAN"
        ]
      },
      "target": "PHYSICAL_FORM",
      "floor": "MARINE_CAPTAIN"
    },
    {
      "cross": false,
      "causeSlot": "DEVIL_FRUIT",
      "when": {
        "kind": "FRUIT_TYPE",
        "fruitTypes": [
          "ZOAN"
        ]
      },
      "target": "PHYSICAL_FORM",
      "floor": "STRONG_FISHMAN"
    },
    {
      "cross": true,
      "causeSlot": "DEVIL_FRUIT",
      "when": {
        "kind": "POWERS",
        "names": [
          "Hito Hito no mi: Model Nika"
        ]
      },
      "target": "HAMON",
      "floor": "ADVANCED"
    },
    {
      "cross": false,
      "causeSlot": "HAMON",
      "when": {
        "kind": "SLOT_MIN",
        "slot": "HAMON",
        "min": "PERFECT"
      },
      "target": "SPIN",
      "floor": "BASIC"
    },
    {
      "cross": true,
      "causeSlot": "HAMON",
      "when": {
        "kind": "SLOT_MIN",
        "slot": "HAMON",
        "min": "PERFECT"
      },
      "target": "ARMAMENT_HAKI",
      "floor": "PRIVATE"
    },
    {
      "cross": true,
      "causeSlot": "HAMON",
      "when": {
        "kind": "SLOT_MIN",
        "slot": "HAMON",
        "min": "ADVANCED"
      },
      "target": "PHYSICAL_FORM",
      "floor": "MARINE_CAPTAIN"
    }
  ],
  "odds": {
    "noStandWeight": 1,
    "noFruitWeight": 1,
    "spin": [
      {
        "level": "NONE",
        "percent": 15
      },
      {
        "level": "BASIC",
        "percent": 30
      },
      {
        "level": "GOLDEN",
        "percent": 30
      },
      {
        "level": "INFINITE",
        "percent": 25
      }
    ],
    "hamon": [
      {
        "level": "NONE",
        "percent": 25
      },
      {
        "level": "BASIC",
        "percent": 35
      },
      {
        "level": "ADVANCED",
        "percent": 35
      },
      {
        "level": "PERFECT",
        "percent": 5
      }
    ],
    "fruitMastery": [
      {
        "level": "REGULAR",
        "percent": 33.33
      },
      {
        "level": "ADVANCED",
        "percent": 33.33
      },
      {
        "level": "AWAKENED",
        "percent": 33.33
      }
    ],
    "physicalForm": [
      {
        "level": "PRIVATE",
        "percent": 16.67
      },
      {
        "level": "STRONG_FISHMAN",
        "percent": 16.67
      },
      {
        "level": "MARINE_CAPTAIN",
        "percent": 16.67
      },
      {
        "level": "VICE_ADMIRAL",
        "percent": 16.67
      },
      {
        "level": "YONKO_COMMANDER",
        "percent": 16.67
      },
      {
        "level": "YONKO_PLUS",
        "percent": 16.67
      }
    ],
    "hakiMastery": [
      {
        "level": "PRIVATE",
        "percent": 25
      },
      {
        "level": "VICE_ADMIRAL",
        "percent": 25
      },
      {
        "level": "YONKO_COMMANDER",
        "percent": 25
      },
      {
        "level": "YONKO_PLUS",
        "percent": 25
      }
    ],
    "hakiSets": [
      {
        "armament": false,
        "observation": false,
        "conqueror": false,
        "percent": 4
      },
      {
        "armament": true,
        "observation": false,
        "conqueror": false,
        "percent": 20
      },
      {
        "armament": false,
        "observation": true,
        "conqueror": false,
        "percent": 20
      },
      {
        "armament": true,
        "observation": true,
        "conqueror": false,
        "percent": 20
      },
      {
        "armament": true,
        "observation": true,
        "conqueror": true,
        "percent": 15
      },
      {
        "armament": true,
        "observation": false,
        "conqueror": true,
        "percent": 10
      },
      {
        "armament": false,
        "observation": true,
        "conqueror": true,
        "percent": 10
      },
      {
        "armament": false,
        "observation": false,
        "conqueror": true,
        "percent": 1
      }
    ],
    "hakiPresence": {
      "armament": 65,
      "observation": 65,
      "conqueror": 36
    }
  },
  "battleIQ": [
    {
      "key": "EXTREMELY_LOW",
      "lo": 0,
      "hi": 69,
      "percent": 2
    },
    {
      "key": "BORDERLINE",
      "lo": 70,
      "hi": 79,
      "percent": 7
    },
    {
      "key": "LOW_AVERAGE",
      "lo": 80,
      "hi": 89,
      "percent": 16
    },
    {
      "key": "AVERAGE",
      "lo": 90,
      "hi": 109,
      "percent": 50
    },
    {
      "key": "HIGH_AVERAGE",
      "lo": 110,
      "hi": 119,
      "percent": 16
    },
    {
      "key": "SUPERIOR",
      "lo": 120,
      "hi": 129,
      "percent": 7
    },
    {
      "key": "VERY_SUPERIOR",
      "lo": 130,
      "hi": 255,
      "percent": 2
    }
  ],
  "conventions": [
    {
      "id": "SEE_STANDS",
      "category": "VISIBILITY",
      "actors": [
        {
          "kind": "ANY_STAND"
        },
        {
          "kind": "SLOT_MIN",
          "slot": "SPIN",
          "min": "BASIC"
        },
        {
          "kind": "SLOT_MIN",
          "slot": "OBSERVATION_HAKI",
          "min": "PRIVATE"
        }
      ],
      "targets": [
        {
          "kind": "ANY_STAND"
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "TOUCH_LOGIA",
      "category": "CONTACT",
      "actors": [
        {
          "kind": "SLOT_MIN",
          "slot": "ARMAMENT_HAKI",
          "min": "PRIVATE"
        },
        {
          "kind": "ANY_STAND"
        },
        {
          "kind": "SLOT_MIN",
          "slot": "SPIN",
          "min": "GOLDEN"
        }
      ],
      "targets": [
        {
          "kind": "FRUIT_TYPE",
          "fruitTypes": [
            "LOGIA"
          ]
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "TOUCH_LOGIA_HAMON",
      "category": "CONTACT",
      "actors": [
        {
          "kind": "SLOT_MIN",
          "slot": "HAMON",
          "min": "BASIC"
        }
      ],
      "targets": [
        {
          "kind": "FRUIT_TYPE",
          "fruitTypes": [
            "LOGIA"
          ]
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": true
    },
    {
      "id": "DAMAGE_STAND",
      "category": "CONTACT",
      "actors": [
        {
          "kind": "ANY_STAND"
        },
        {
          "kind": "SLOT_MIN",
          "slot": "ARMAMENT_HAKI",
          "min": "PRIVATE"
        },
        {
          "kind": "SLOT_MIN",
          "slot": "CONQUEROR_HAKI",
          "min": "PRIVATE"
        },
        {
          "kind": "FRUIT_TYPE",
          "fruitTypes": [
            "LOGIA"
          ]
        },
        {
          "kind": "SLOT_MIN",
          "slot": "SPIN",
          "min": "BASIC"
        }
      ],
      "targets": [
        {
          "kind": "ANY_STAND"
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "TIME_STOP",
      "category": "TIME",
      "actors": [
        {
          "kind": "POWERS",
          "names": [
            "The World",
            "Star Platinum: The World",
            "The World (Steel Ball Run)",
            "King Crimson"
          ],
          "group": "TIME_STOPPERS"
        }
      ],
      "targets": [],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "MOVE_IN_TIME_STOP",
      "category": "TIME",
      "actors": [
        {
          "kind": "POWERS",
          "names": [
            "The World",
            "Star Platinum: The World",
            "The World (Steel Ball Run)",
            "King Crimson"
          ],
          "group": "TIME_STOPPERS"
        },
        {
          "kind": "SLOT_MIN",
          "slot": "SPIN",
          "min": "INFINITE"
        },
        {
          "kind": "SLOT_MIN",
          "slot": "CONQUEROR_HAKI",
          "min": "YONKO_PLUS"
        }
      ],
      "targets": [
        {
          "kind": "POWERS",
          "names": [
            "The World",
            "Star Platinum: The World",
            "The World (Steel Ball Run)",
            "King Crimson"
          ],
          "group": "TIME_STOPPERS"
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "MADE_IN_HEAVEN_STOPPED_BY",
      "category": "TIME",
      "actors": [
        {
          "kind": "POWERS",
          "names": [
            "The World",
            "Star Platinum: The World",
            "The World (Steel Ball Run)",
            "King Crimson"
          ],
          "group": "TIME_STOPPERS"
        }
      ],
      "targets": [
        {
          "kind": "POWERS",
          "names": [
            "Made in Heaven"
          ]
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "MADE_IN_HEAVEN_KEEP_PACE",
      "category": "TIME",
      "actors": [
        {
          "kind": "SLOT_MIN",
          "slot": "SPIN",
          "min": "INFINITE"
        }
      ],
      "targets": [
        {
          "kind": "POWERS",
          "names": [
            "Made in Heaven"
          ]
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "MADE_IN_HEAVEN_SLOWED_BY",
      "category": "TIME",
      "actors": [
        {
          "kind": "SLOT_MIN",
          "slot": "CONQUEROR_HAKI",
          "min": "YONKO_PLUS"
        }
      ],
      "targets": [
        {
          "kind": "POWERS",
          "names": [
            "Made in Heaven"
          ]
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "MADE_IN_HEAVEN_TRACKED_BY",
      "category": "TIME",
      "actors": [
        {
          "kind": "SLOT_MIN",
          "slot": "OBSERVATION_HAKI",
          "min": "YONKO_PLUS"
        }
      ],
      "targets": [
        {
          "kind": "POWERS",
          "names": [
            "Made in Heaven"
          ]
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "CONQUEROR_KNOCKOUT",
      "category": "WILL",
      "actors": [
        {
          "kind": "SLOT_MIN",
          "slot": "CONQUEROR_HAKI",
          "min": "PRIVATE"
        }
      ],
      "targets": [],
      "immune": [
        {
          "kind": "SLOT_MIN",
          "slot": "SPIN",
          "min": "INFINITE"
        }
      ],
      "attenuated": [
        {
          "kind": "SLOT_MIN",
          "slot": "HAMON",
          "min": "PERFECT"
        }
      ],
      "gap": 2,
      "judgement": false
    },
    {
      "id": "CONQUEROR_HINDER",
      "category": "WILL",
      "actors": [
        {
          "kind": "SLOT_MIN",
          "slot": "CONQUEROR_HAKI",
          "min": "PRIVATE"
        }
      ],
      "targets": [],
      "immune": [
        {
          "kind": "SLOT_MIN",
          "slot": "SPIN",
          "min": "INFINITE"
        }
      ],
      "attenuated": [
        {
          "kind": "SLOT_MIN",
          "slot": "HAMON",
          "min": "PERFECT"
        }
      ],
      "gap": 1,
      "judgement": false
    },
    {
      "id": "WATER_WEAKNESS",
      "category": "WEAKNESS",
      "actors": [
        {
          "kind": "POWERS",
          "names": [
            "Weather Report"
          ]
        }
      ],
      "targets": [
        {
          "kind": "ANY_FRUIT"
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "YAMI_NULLIFIES",
      "category": "NULLIFICATION",
      "actors": [
        {
          "kind": "POWERS",
          "names": [
            "Yami Yami no mi"
          ]
        }
      ],
      "targets": [
        {
          "kind": "ANY_FRUIT"
        },
        {
          "kind": "ANY_STAND"
        }
      ],
      "immune": [
        {
          "kind": "POWERS",
          "names": [
            "Gold Experience: Requiem",
            "Wonder of U",
            "D4C: Love Train",
            "Tusk: Act 4"
          ],
          "group": "ABSOLUTE_STANDS"
        },
        {
          "kind": "POWERS",
          "names": [
            "Soft \u0026 Wet: Go Beyond"
          ]
        },
        {
          "kind": "POWERS",
          "names": [
            "The World",
            "Star Platinum: The World",
            "The World (Steel Ball Run)",
            "King Crimson"
          ],
          "group": "TIME_STOPPERS"
        },
        {
          "kind": "POWERS",
          "names": [
            "Made in Heaven"
          ]
        }
      ],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "SPIN_INFINITE_SUPREME",
      "category": "SUPREMACY",
      "actors": [
        {
          "kind": "SLOT_MIN",
          "slot": "SPIN",
          "min": "INFINITE"
        }
      ],
      "targets": [],
      "immune": [
        {
          "kind": "POWERS",
          "names": [
            "Gold Experience: Requiem"
          ]
        },
        {
          "kind": "SLOT_MIN",
          "slot": "SPIN",
          "min": "INFINITE"
        },
        {
          "kind": "POWERS",
          "names": [
            "Wonder of U"
          ]
        }
      ],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "SPIN_INFINITE_DUEL",
      "category": "SUPREMACY",
      "actors": [
        {
          "kind": "SLOT_MIN",
          "slot": "SPIN",
          "min": "INFINITE"
        }
      ],
      "targets": [
        {
          "kind": "SLOT_MIN",
          "slot": "SPIN",
          "min": "INFINITE"
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": true
    },
    {
      "id": "ABSOLUTE_GER",
      "category": "SUPREMACY",
      "actors": [
        {
          "kind": "POWERS",
          "names": [
            "Soft \u0026 Wet: Go Beyond"
          ]
        }
      ],
      "targets": [
        {
          "kind": "POWERS",
          "names": [
            "Gold Experience: Requiem"
          ]
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "ABSOLUTE_WONDER_OF_U",
      "category": "SUPREMACY",
      "actors": [
        {
          "kind": "POWERS",
          "names": [
            "Soft \u0026 Wet: Go Beyond",
            "Gold Experience: Requiem"
          ]
        }
      ],
      "targets": [
        {
          "kind": "POWERS",
          "names": [
            "Wonder of U"
          ]
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "ABSOLUTE_LOVE_TRAIN",
      "category": "SUPREMACY",
      "actors": [
        {
          "kind": "SLOT_MIN",
          "slot": "SPIN",
          "min": "INFINITE"
        },
        {
          "kind": "POWERS",
          "names": [
            "Gold Experience: Requiem",
            "Soft \u0026 Wet: Go Beyond",
            "Wonder of U"
          ]
        }
      ],
      "targets": [
        {
          "kind": "POWERS",
          "names": [
            "D4C: Love Train"
          ]
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    },
    {
      "id": "ABSOLUTE_TUSK_ACT_4",
      "category": "SUPREMACY",
      "actors": [
        {
          "kind": "POWERS",
          "names": [
            "Gold Experience: Requiem",
            "Wonder of U"
          ]
        }
      ],
      "targets": [
        {
          "kind": "POWERS",
          "names": [
            "Tusk: Act 4"
          ]
        }
      ],
      "immune": [],
      "attenuated": [],
      "gap": 0,
      "judgement": false
    }
  ]
} as const

export type ManualRules = typeof MANUAL_RULES
