// Code generated by cmd/typegen. DO NOT EDIT.
//
// Source of truth: apps/backend/internal/infrastructure/api/dto and
// apps/backend/internal/domain/enums. Regenerate with `make types` from
// apps/backend (or `make types-docker`). CI fails if this file is stale.

import { z } from 'zod'
import { gameResultResponseSchema, gameStateResponseSchema, updateConfigPayloadSchema } from './dto'
import { errorResponseSchema } from './errors'

export const addBotPayloadSchema = z.object({
  teamId: z.string(),
})
export type AddBotPayload = z.infer<typeof addBotPayloadSchema>

export const gameAbortedPayloadSchema = z.object({
  reason: z.string(),
})
export type GameAbortedPayload = z.infer<typeof gameAbortedPayloadSchema>

export const hostReassignedPayloadSchema = z.object({
  newHostId: z.string(),
})
export type HostReassignedPayload = z.infer<typeof hostReassignedPayloadSchema>

export const kickPayloadSchema = z.object({
  participantId: z.string(),
})
export type KickPayload = z.infer<typeof kickPayloadSchema>

export const loadoutsAssignedPayloadSchema = z.object({
  roundIndex: z.number().int(),
  revealMs: z.number().int(),
})
export type LoadoutsAssignedPayload = z.infer<typeof loadoutsAssignedPayloadSchema>

export const lobbyLockChangedPayloadSchema = z.object({
  locked: z.boolean(),
})
export type LobbyLockChangedPayload = z.infer<typeof lobbyLockChangedPayloadSchema>

export const movePlayerPayloadSchema = z.object({
  participantId: z.string(),
  teamId: z.string(),
})
export type MovePlayerPayload = z.infer<typeof movePlayerPayloadSchema>

export const gameFinishedPayloadSchema = z.object({
  result: gameResultResponseSchema,
})
export type GameFinishedPayload = z.infer<typeof gameFinishedPayloadSchema>

export const playerJoinedPayloadSchema = z.object({
  participantId: z.string(),
})
export type PlayerJoinedPayload = z.infer<typeof playerJoinedPayloadSchema>

export const playerKickedPayloadSchema = z.object({
  participantId: z.string(),
})
export type PlayerKickedPayload = z.infer<typeof playerKickedPayloadSchema>

export const playerLeftPayloadSchema = z.object({
  participantId: z.string(),
})
export type PlayerLeftPayload = z.infer<typeof playerLeftPayloadSchema>

export const rematchReadyPayloadSchema = z.object({
  gameId: z.string(),
})
export type RematchReadyPayload = z.infer<typeof rematchReadyPayloadSchema>

export const removeBotPayloadSchema = z.object({
  botId: z.string(),
})
export type RemoveBotPayload = z.infer<typeof removeBotPayloadSchema>

export const resyncRequiredPayloadSchema = z.object({
  reason: z.string(),
})
export type ResyncRequiredPayload = z.infer<typeof resyncRequiredPayloadSchema>

export const revealReadyChangedPayloadSchema = z.object({
  ready: z.number().int(),
  total: z.number().int(),
})
export type RevealReadyChangedPayload = z.infer<typeof revealReadyChangedPayloadSchema>

export const roundResolvedPayloadSchema = z.object({
  roundIndex: z.number().int(),
  winner: z.string(),
  decidedByCoinFlip: z.boolean(),
})
export type RoundResolvedPayload = z.infer<typeof roundResolvedPayloadSchema>

export const setLockPayloadSchema = z.object({
  locked: z.boolean(),
})
export type SetLockPayload = z.infer<typeof setLockPayloadSchema>

export const summaryOpenedPayloadSchema = z.object({
  roundIndex: z.number().int(),
  closesAt: z.iso.datetime({ offset: true }),
})
export type SummaryOpenedPayload = z.infer<typeof summaryOpenedPayloadSchema>

export const summaryReadyChangedPayloadSchema = z.object({
  ready: z.number().int(),
  total: z.number().int(),
})
export type SummaryReadyChangedPayload = z.infer<typeof summaryReadyChangedPayloadSchema>

export const switchTeamPayloadSchema = z.object({
  participantId: z.string().optional(),
  teamId: z.string(),
})
export type SwitchTeamPayload = z.infer<typeof switchTeamPayloadSchema>

export const teamChangedPayloadSchema = z.object({
  participantId: z.string(),
  fromTeamId: z.string(),
  toTeamId: z.string(),
})
export type TeamChangedPayload = z.infer<typeof teamChangedPayloadSchema>

export const tiebreakOpenedPayloadSchema = z.object({
  roundIndex: z.number().int(),
  closesAt: z.iso.datetime({ offset: true }),
})
export type TiebreakOpenedPayload = z.infer<typeof tiebreakOpenedPayloadSchema>

export const transferHostPayloadSchema = z.object({
  participantId: z.string(),
})
export type TransferHostPayload = z.infer<typeof transferHostPayloadSchema>

export const voteCastPayloadSchema = z.object({
  roundIndex: z.number().int(),
  votesCast: z.number().int(),
  voters: z.number().int(),
})
export type VoteCastPayload = z.infer<typeof voteCastPayloadSchema>

export const votePayloadSchema = z.object({
  option: z.string(),
})
export type VotePayload = z.infer<typeof votePayloadSchema>

export const votingOpenedPayloadSchema = z.object({
  roundIndex: z.number().int(),
  closesAt: z.iso.datetime({ offset: true }),
})
export type VotingOpenedPayload = z.infer<typeof votingOpenedPayloadSchema>

export const CLIENT_COMMAND = {
  LEAVE: 'LEAVE',
  ADD_BOT: 'ADD_BOT',
  REMOVE_BOT: 'REMOVE_BOT',
  START: 'START',
  ABORT: 'ABORT',
  VOTE: 'VOTE',
  RESYNC: 'RESYNC',
  SWITCH_TEAM: 'SWITCH_TEAM',
  MOVE_PLAYER: 'MOVE_PLAYER',
  KICK: 'KICK',
  TRANSFER_HOST: 'TRANSFER_HOST',
  SET_LOCK: 'SET_LOCK',
  UPDATE_CONFIG: 'UPDATE_CONFIG',
  REVEAL_READY: 'REVEAL_READY',
  SUMMARY_READY: 'SUMMARY_READY',
  REMATCH: 'REMATCH',
} as const

export type ClientCommandType = (typeof CLIENT_COMMAND)[keyof typeof CLIENT_COMMAND]

export const clientCommandSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal(CLIENT_COMMAND.LEAVE),
    requestId: z.string().optional(),
    payload: z.object({}).optional(),
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.ADD_BOT),
    requestId: z.string().optional(),
    payload: addBotPayloadSchema,
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.REMOVE_BOT),
    requestId: z.string().optional(),
    payload: removeBotPayloadSchema,
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.START),
    requestId: z.string().optional(),
    payload: z.object({}).optional(),
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.ABORT),
    requestId: z.string().optional(),
    payload: z.object({}).optional(),
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.VOTE),
    requestId: z.string().optional(),
    payload: votePayloadSchema,
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.RESYNC),
    requestId: z.string().optional(),
    payload: z.object({}).optional(),
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.SWITCH_TEAM),
    requestId: z.string().optional(),
    payload: switchTeamPayloadSchema,
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.MOVE_PLAYER),
    requestId: z.string().optional(),
    payload: movePlayerPayloadSchema,
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.KICK),
    requestId: z.string().optional(),
    payload: kickPayloadSchema,
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.TRANSFER_HOST),
    requestId: z.string().optional(),
    payload: transferHostPayloadSchema,
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.SET_LOCK),
    requestId: z.string().optional(),
    payload: setLockPayloadSchema,
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.UPDATE_CONFIG),
    requestId: z.string().optional(),
    payload: updateConfigPayloadSchema,
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.REVEAL_READY),
    requestId: z.string().optional(),
    payload: z.object({}).optional(),
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.SUMMARY_READY),
    requestId: z.string().optional(),
    payload: z.object({}).optional(),
  }),
  z.object({
    type: z.literal(CLIENT_COMMAND.REMATCH),
    requestId: z.string().optional(),
    payload: z.object({}).optional(),
  }),
])
export type ClientCommand = z.infer<typeof clientCommandSchema>

export const SERVER_FRAME = {
  STATE: 'STATE',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  HOST_REASSIGNED: 'HOST_REASSIGNED',
  GAME_STARTED: 'GAME_STARTED',
  LOADOUTS_ASSIGNED: 'LOADOUTS_ASSIGNED',
  VOTING_OPENED: 'VOTING_OPENED',
  VOTE_CAST: 'VOTE_CAST',
  TIEBREAK_OPENED: 'TIEBREAK_OPENED',
  ROUND_RESOLVED: 'ROUND_RESOLVED',
  GAME_FINISHED: 'GAME_FINISHED',
  GAME_ABORTED: 'GAME_ABORTED',
  ERROR: 'ERROR',
  RESYNC_REQUIRED: 'RESYNC_REQUIRED',
  TEAM_CHANGED: 'TEAM_CHANGED',
  PLAYER_KICKED: 'PLAYER_KICKED',
  LOBBY_LOCK_CHANGED: 'LOBBY_LOCK_CHANGED',
  CONFIG_UPDATED: 'CONFIG_UPDATED',
  REVEAL_READY_CHANGED: 'REVEAL_READY_CHANGED',
  SUMMARY_OPENED: 'SUMMARY_OPENED',
  SUMMARY_READY_CHANGED: 'SUMMARY_READY_CHANGED',
  REMATCH_READY: 'REMATCH_READY',
} as const

export type ServerFrameType = (typeof SERVER_FRAME)[keyof typeof SERVER_FRAME]

export const serverFrameSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal(SERVER_FRAME.STATE),
    requestId: z.string().optional(),
    payload: gameStateResponseSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.PLAYER_JOINED),
    requestId: z.string().optional(),
    payload: playerJoinedPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.PLAYER_LEFT),
    requestId: z.string().optional(),
    payload: playerLeftPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.HOST_REASSIGNED),
    requestId: z.string().optional(),
    payload: hostReassignedPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.GAME_STARTED),
    requestId: z.string().optional(),
    payload: z.object({}).optional(),
  }),
  z.object({
    type: z.literal(SERVER_FRAME.LOADOUTS_ASSIGNED),
    requestId: z.string().optional(),
    payload: loadoutsAssignedPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.VOTING_OPENED),
    requestId: z.string().optional(),
    payload: votingOpenedPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.VOTE_CAST),
    requestId: z.string().optional(),
    payload: voteCastPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.TIEBREAK_OPENED),
    requestId: z.string().optional(),
    payload: tiebreakOpenedPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.ROUND_RESOLVED),
    requestId: z.string().optional(),
    payload: roundResolvedPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.GAME_FINISHED),
    requestId: z.string().optional(),
    payload: gameFinishedPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.GAME_ABORTED),
    requestId: z.string().optional(),
    payload: gameAbortedPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.ERROR),
    requestId: z.string().optional(),
    payload: errorResponseSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.RESYNC_REQUIRED),
    requestId: z.string().optional(),
    payload: resyncRequiredPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.TEAM_CHANGED),
    requestId: z.string().optional(),
    payload: teamChangedPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.PLAYER_KICKED),
    requestId: z.string().optional(),
    payload: playerKickedPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.LOBBY_LOCK_CHANGED),
    requestId: z.string().optional(),
    payload: lobbyLockChangedPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.CONFIG_UPDATED),
    requestId: z.string().optional(),
    payload: z.object({}).optional(),
  }),
  z.object({
    type: z.literal(SERVER_FRAME.REVEAL_READY_CHANGED),
    requestId: z.string().optional(),
    payload: revealReadyChangedPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.SUMMARY_OPENED),
    requestId: z.string().optional(),
    payload: summaryOpenedPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.SUMMARY_READY_CHANGED),
    requestId: z.string().optional(),
    payload: summaryReadyChangedPayloadSchema,
  }),
  z.object({
    type: z.literal(SERVER_FRAME.REMATCH_READY),
    requestId: z.string().optional(),
    payload: rematchReadyPayloadSchema,
  }),
])
export type ServerFrame = z.infer<typeof serverFrameSchema>
